### ISSUE TITLE
Difference between SdlDisconnectedReason and AppInterfaceUnregisteredReason?

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#100]
What is the difference between these two enums?  Their enum definitions are very similar, but it's unclear what the difference is between these two enums.

[SdlDisconnectedReason](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/SdlDisconnectedReason.java#L29-69) has a method that converts a AppInterfaceUnregisteredReason to a SdlDisconnectedReason, but doesn't contain every possibility.  I'm trying to figure out if this step is really necessary or if we can utilize the same enum instead of duplicating a bunch of values.

**Comment by mrapitis** [comment]
SdlDisconnectedReason should be a superset of AppInterfaceUnregisteredReason.  If there are items missing, they should be added.  You have probably already noticed, but SdlDisconnectedReason also contains additional elements not specified in AppInterfaceUnregisteredReason that are used for various conditions that have resulted in a disconnect from sdl core.
