### ISSUE TITLE
Issue with creation of valid UnsubscribeVehicleData request with cloudAppVehicleID parameter

### ISSUE THREAD

**Issue by aderiabin** [smartdevicelink/sdl_android#1026]
### Bug Report
It is not possible to create valid UnsubscribeVehicleData request with cloudAppVehicleID parameter because UnsubscribeVehicleData has no method to set property cloudAppVehicleID

##### Reproduction Steps
1. Issue is observed on application development phase (see Sample code section )

##### Expected Behavior
UnsubscribeVehicleData class provides possibility to set property cloudAppVehicleID for UnsubscribeVehicleData request

##### Observed Behavior
UnsubscribeVehicleData class does not provide possibility to set property cloudAppVehicleID for UnsubscribeVehicleData request

##### OS & Version Information
* Android Version: Any
* SDL Android Version: 4.8.0-rc1
* Testing Against: N/A

##### Test Case, Sample Code, and / or Example App
Code:
```
UnsubscribeVehicleData request = new UnsubscribeVehicleData();
request.setSpeed(true) // OK
request.setCloudAppVehicleID(true) // Error: no such method
sdlManager.sendRPC(request);
```

**Comment by aderiabin** [comment]
@theresalech please triage this issue

**Comment by joeygrover** [comment]
Fixed with https://github.com/smartdevicelink/sdl_android/pull/1027
