### ISSUE TITLE
Discrepancies present in PublishAppService.json including uriPrefix, uriScheme

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#1029]
### Bug Report
In the release/4.8.0-rc1 branch the uriPrefix, uriScheme may have been added to PublishAppService.json in anticipation for https://github.com/smartdevicelink/sdl_evolution/issues/678, however they are not currently included in the AppServiceManifest structure.

Also the "handledRPCs":["ButtonPress"] field currently contains an incorrect type... the handledRPCs field contains the Function IDs for the RPCs as list of integers but in the PublishAppService,json file it is a list of strings.

**Comment by joeygrover** [comment]
uriPrefix and uriScheme were part of the original proposal and they are entered with the structure defined there, but the proposal you linked had a vote to remove them as the author (me) didn't see them as sufficient in their original state (see [this commit](https://github.com/smartdevicelink/sdl_evolution/commit/c0690d3845ee30e6ec4cffdb8ca59ba58b48bcd2#diff-1a98c83a72c41981ededa253a21d0232)). Also the functionID's would have been "enums" but in JSON they are entered as strings. Both of those items were altered post the original acceptance of the feature as well as the development of the feature for the platform. The json files are also only for unit tests. However, the json file should be updated.
