### ISSUE TITLE
BulkData ignores null inputs

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#103]
The [setBulkData](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/RPCStruct.java#L61-67) method in RPCStruct ignores null values.  So, once a value is set for bulk data, it can never be removed unless a new array is passed in.

**Comment by yifili09** [comment]
@mikeburke106 Would it affect the usb bulk transfer(AOA)?
There is an issue about App(comply sdl_android_proxy V3.1.2 ) can not read huge amount of data sometimes from Audio Head Unit(integrated SDL 3.5) by one of our partner.  We are still working on it. Thanks.

**Comment by mikeburke106** [comment]
No, this issue isn't related to any core issues or data transfers, it's only a concern for Android developer-facing API.  Once bulk data is set for a message, it can never be removed with the current implementation.
