### ISSUE TITLE
Implement TBT APIs

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#109]
The proxy is currently missing the following APIs in the spec and need to be implemented:

  * [AlertManeuver (and response)](https://github.com/smartdevicelink/sdl_core/blob/46ed776c537131e72747538488b213cf45f23e22/src/components/interfaces/MOBILE_API.xml#L4189-4221)
  * [UpdateTurnList (and response)](https://github.com/smartdevicelink/sdl_core/blob/46ed776c537131e72747538488b213cf45f23e22/src/components/interfaces/MOBILE_API.xml#L4223-4251)
  * [ShowConstantTBT (and response)](https://github.com/smartdevicelink/sdl_core/blob/46ed776c537131e72747538488b213cf45f23e22/src/components/interfaces/MOBILE_API.xml#L4126-4187)

**Comment by mrapitis** [comment]
We need to reopen this issue as none of the tbt RPC responses have been handled in SdlProxyBase.java.

An example of handling the RPC responses can be found here as seen in SdlProxyBase.java DialNumber and SendLocation here:

https://github.com/smartdevicelink/sdl_android/commit/d8a8088e0fb676e8b60c0ca4d38d35eb257c0882
