### ISSUE TITLE
What happens when correlation ID of an app approaches max correlation ID?

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#126]
I noticed today that some correlation IDs are "reserved" for specific tasks and I'm wondering what is supposed to happen if an app sends so many messages that its correlation ID reaches these reserved values.

From SdlProxyBase.java:

```java
// Protected Correlation IDs
private final int 	REGISTER_APP_INTERFACE_CORRELATION_ID = 65529,
				UNREGISTER_APP_INTERFACE_CORRELATION_ID = 65530,
				POLICIES_CORRELATION_ID = 65535;
```

I ran a quick test and here is what I'm seeing:

  * Send SubscribeButton request with correlation ID 65528
    * SubscribeButton response is SUCCESS
  * Send SubscribeButton request with correlation ID 65529 (reserved)
    * SubscribeButton response doesn't come through the proxy due to logic in SdlProxyBase `handleRPCMessage`.  __This makes it look as if our message was ignored by core.__
  * Send SubscribeButton request with correlation ID 65536 (above limit)
    * SubscribeButton response is REJECTED

Is this desired behavior?  Are app developers supposed to re-set their correlation ID counter when it reaches 65528?

I think we should encapsulate correlation ID generation into a class and abstract this whole concept from developers.  The mobile libs should be able to handle all ID generation and then we can handle whatever is supposed to happen when correlation IDs approach this 65535 limit without putting that burden on developers.

**Comment by Heath-FoMoCo** [comment]
I agree.  All of our internal frameworks abstract this concept.  We will be moving these efforts to the open soon.

**Comment by mikeburke106** [comment]
Ok, sounds good.  Is the behavior I described what we would expect?  Does the new framework rollover correlation ID values to prevent hitting this reserved range?

**Comment by justinjdickow** [comment]
I'd also like to point out that the specification gives Correlation ID 4 Bytes in the Binary Header and says that the valid range is 0x00000000 - 0xFFFFFFFF. Does this need to be updated?

**Comment by mikeburke106** [comment]
I think we now have the answer to this question.  Legacy software (Gen 1.1) will reject any correlation IDs greater than 2 bytes, but current software allows up to 4 bytes.  However, there are "reserved" correlation IDs at the high-end of the 2 byte values, which must be skipped over by developers.  This isn't documented anywhere, so it needs to be documented and abstracted so the developer doesn't have to worry about these corner-case details.

**Comment by justinjdickow** [comment]
Where should this information be documented?

**Comment by mikeburke106** [comment]
We have the backwards compatibility issues documented in #90.  We should probably have a specialized document for corner cases and legacy issues that need to be supported.

**Comment by joeygrover** [comment]
Agreed. I attempted to start a post #90 , but it is very incomplete. We should continue to add anything we find to this post so we can get them documented.
