### ISSUE TITLE
Purpose of NGN media app name?

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#129]
In the MOBILE_API.xml spec, there are 2 types of app name - "appName" and "ngnMediaScreenAppName".  I understand that NGN Media Screen App Name is supposed to be a "shorter" name for systems that don't support scrolling text and only have a limited number of characters to display.

However, the spec says both of these app names have a max length of 100 characters:

```xml
    <param name="appName" type="String" maxlength="100" mandatory="false">
      <description>Request new app name registration</description>
    </param>

    <param name="ngnMediaScreenAppName" type="String" maxlength="100" mandatory="false">
      <description>Request new app short name registration</description>
    </param>
```

If NGN app name is supposed to be shorter, why is the max length the same?  Why was NGN media app name added to the protocol instead of just truncating the regular app name to fit on the head-unit side?

**Comment by stefanek22** [comment]
ngnMediaScreenAppName is a legacy parameter from the v1 headunits.  It was used in lieu of truncating the appName itself to allow a more custom short name (e.g. Streaming Media Player could be "SMP" instead of "STREA").

The maxlength for most strings originally was arbitrarily set higher as a definite ceiling was unknown.

**Comment by mikeburke106** [comment]
So, should the ngnMediaScreenAppName be deprecated in the libraries?

**Comment by Heath-FoMoCo** [comment]
My opinion is no.   It is still required by our older head units.  It is still something that every app should/could use to avoid unwanted names on the head unit.  It still functions as a valid call.

**Comment by mikeburke106** [comment]
What are the guidelines for developers in terms of setting this name since there is no real "max size"?  Should this value be 3 characters? 5? 10?  How can developers be sure their NGN name won't be truncated and, thus, look worse than if the actual app name was truncated?  If there is an actual upper limit to the value, we should modify that in the spec.

Also, does NGN stand for something in particular?  Just curious in case anyone asks me.

**Comment by stefanek22** [comment]
The implementation was a max of 5 characters on our legacy systems (older non-nav and nav headunits).  However, the shortened name is also used on our current non-nav headunit to display certain text like "<ngnMediaScreenAppName> Help", etc.  This case leaves the length more open / less defined.

That said, we can urge users to target 5 characters if possible.

Note:  NGN is a legacy term ("Next Gen Nav").

**Comment by mikeburke106** [comment]
Thanks for the info @stefanek22 and @Heath-FoMoCo.  Closing this issue.
