### ISSUE TITLE
Make RPC classes immutable

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#13]
RPC classes are currently mutable objects - there are setter methods that allow the user to change the data within the RPC after creation.  However, within the library, RPC classes are treated as immutable (the library never changes them).  

I propose we make all RPC classes immutable objects.  Doing so would greatly reduce complexity and remove the need for defensive copying of RPC data types since they would be immutable.

Also, the developer would create the object with all data being set in a constructor instead of using setter methods.  This would also make developer code more readable since they can create and initialize an object on a single line instead of creating an empty object and calling setter methods on it.

**Comment by justinjdickow** [comment]
covered by #20
