### ISSUE TITLE
PutFile parameters for offset and length should be longs

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#130]
[PutFile.java](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/PutFile.java) contains methods for getting/setting `offset` and `length` parameters; however, the specification states that these values can be between 0 and 100,000,000,000.  Max integer is 2,174,783,647, which means the spec values cannot be represented as an Integer object.  These values should be changed to __longs__ in the code (and in the spec if necessary).

*EDIT* - Changed doubles to longs in response to @mrapitis comment below.

**Comment by mrapitis** [comment]
I would suggest using Longs for the offset and length parameters (for both putfile and onsystemrequest) as the values will not include decimals.  I have also mentioned this as a limitation for our putfile streaming efforts as well, see TODO below:
https://github.com/mrapitis/sdl_android/blob/update_putfile_stream_enhancements/sdl_android_lib/src/com/smartdevicelink/streaming/StreamRPCPacketizer.java#L127-129

**Comment by joeygrover** [comment]
Resolved, currently in develop branch.
