### ISSUE TITLE
Add real version info into Version.java

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#136]
[Version.java](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/Version.java) doesn't contain any useful information.

This file should contain something similar to Android's [Build.VERSION_CODES](http://developer.android.com/reference/android/os/Build.VERSION_CODES.html) class.  Any references to a version within the library should use these defined version codes instead of "magic numbers".

**Comment by justinjdickow** [comment]
There is a build process that changes this value before being distributed

**Comment by joeygrover** [comment]
This has been added to the project's gradle setup.
