### ISSUE TITLE
Remove unused classes

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#141]
The following classes are unused:

  * [StringEnumer](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/util/StringEnumer.java)
  * [Base64](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/util/Base64.java)
  * [Mime](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/util/Mime.java)

**Comment by MikaylaRay44** [comment]
com/smartdevicelink/proxy/interfaces/IProxyListenerALM

Should also be on the list of classes to be removed, since all of its method stubs were moved to IProxyListenerBase.
