### ISSUE TITLE
Fix logic in getLockScreenStatus

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#142]
I mentioned this in a [previous pull request](https://github.com/smartdevicelink/sdl_android/pull/33#issuecomment-60675729).

The logic in `getLockScreenStatus` method in [LockScreenManager.java](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/LockScreenManager.java#L52-92) is really messy and needs to be cleaned up for readability and maintainability.

**Comment by joeygrover** [comment]
A new lockscreen manager has been created. No longer an issue.
