### ISSUE TITLE
LockScreenManager setHMILevel method has side-effects

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#143]
[LockScreenManager.java](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/LockScreenManager.java#L30-38) method `setHMILevel` has side-effects, which is bad practice.

``` java
    public synchronized void setHMILevel(HMILevel hmiVal)
    {       
        hmiLevel = hmiVal;

        if ( (hmiVal.equals(HMILevel.HMI_FULL)) || (hmiVal.equals(HMILevel.HMI_LIMITED)) )
            setUserSelectedStatus(true);
        else if (hmiVal.equals(HMILevel.HMI_NONE))
            setUserSelectedStatus(false);               
    }
```

The method signature indicates that it will set the HMI level to the value that is passed in; however, it has the side-effect of setting the user selected variable based on the input HMI level, which is not the responsibility of a setter method.

**Comment by mikeburke106** [comment]
This side-effect also causes a NullPointerException when null is passed into this method.

**Comment by mikeburke106** [comment]
Since the user selected variable is entirely dependent on the HMI level, not only can it be omitted from the setter method, it should also simplify the logic in `getLockScreenStatus`.

**Comment by joeygrover** [comment]
A new lockscreen manager has been created. No longer an issue.
