### ISSUE TITLE
LockScreenManager setter methods are inconsistent

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#145]
[LockScreenManager.java](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/LockScreenManager.java) stores `bUserSelected` and `bDriverDistStatus` as boolean objects, but setter methods take in boolean primitives.  This makes it impossible to set values back to null after they have been set to a value.

Setter methods should be consistent with variable declarations - either both objects or both primitives.

**Comment by mrapitis** [comment]
While I agree that having setters with consistent data types is best practice, are you sure that setting the value back to null after having a value assigned is impossible?

The following code should execute without error:
```		
		Boolean tempObject = null;
		boolean tempPrimitive = false;
		tempObject = tempPrimitive;
		tempObject = null;
```

**Comment by joeygrover** [comment]
The user is unable to set to null because the method signature takes in a primitive boolean, therefore it will not compile if the user tries to pass in null.

**Comment by mikeburke106** [comment]
[Here is the failed unit test for this case.](https://github.com/crokita/sdl_android/blob/3807614d9f09452b8cd819cc0f03445badb4b51a/sdl_android_tests/src/com/smartdevicelink/test/proxy/LockScreenManagerTest.java#L21-22)

It doesn't even compile, let alone work.

**Comment by mrapitis** [comment]
@joeygrover thanks for clearing that up.  @mikeburke106 I misunderstood your initial concern.

**Comment by joeygrover** [comment]
A new lockscreen manager has been created. No longer an issue.
