### ISSUE TITLE
onProxyClosed not always received in app multiplexing scenarios

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#152]
When a transport error occurs (such as bt disconnect), an onProxyClosed notification should be sent to each multiplexed app.  Sometimes a concurrent modification exception occurs in the InternalMsgDispatcher class that prevents the onTransportError method from being called.  As a result, the onProxyClosed method is never called and the app never receives the notification.  The listenerlist Vector in SdlConnection needs to be changed to a list that is thread safe.  The logic in the onTransportError for loop also need to be revised.

**Comment by joeygrover** [comment]
Is this for #151 feature/multiplexing?

**Comment by mrapitis** [comment]
Hey Joey,
The problem affects the internal multiplexing functionality on the master and develop branches (that is already implemented), its not specific to the feature changes in #151.

**Comment by joeygrover** [comment]
Ok, just making sure. Thanks!

**Comment by joeygrover** [comment]
Merged.
