### ISSUE TITLE
PerformInteraction returns INVALID_ID on 2nd invocation

### ISSUE THREAD

**Issue by diosceles** [smartdevicelink/sdl_android#156]
Scenario:

When sending a PerformInteraction command to the TDK with a given set of choices, the behavior is normal on the first invocation of the PerformInteraction.  However, when rendering the choices for a second time, the onPerformInteractionResponse callback is invoked immediately, with a result code of "INVALID_ID"

Setup:

  1) Define a list of Choices:

```java
mProxyALM.createInteractionChoiceSet(choices,choiceSet1IndexValue,autoIncCorrId++);
```

  2) Render PerformInteraction with the choices:

```java
mProxyALM.performInteraction(initialPrompt,displayText,choiceSet1IndexValue,"help","" +
                    "screen has timed out",InteractionMode.MANUAL_ONLY,30000,autoIncCorrId++);
```

  3) The PerformInteraction renders normally.  Select any choice.
  4) Render the choice list again:

```java
mProxyALM.performInteraction(initialPrompt,displayText,choiceSet1IndexValue,"help","" +
                    "screen has timed out",InteractionMode.MANUAL_ONLY,30000,autoIncCorrId++);
```

Expected result:  The PerformInteraction screen should render on the TDK with the earlier defined choices.

Actual result: No rendering is done.  onPerformInteractionResponse callback is invoked immediately, with a result code of INVALID_ID

**Comment by justinjdickow** [comment]
I'm not able to reproduce this issue at least with the Android SPT, I tried choices with `BOTH` and `MANUAL_ONLY` interaction modes, they show up every time, and I always get call backs for the choices being selected.

@diosceles How many choices are in the choice set you're using?

@mrapitis Maybe there is something about how the `performInteraction` is being used in this example that I'm missing?

**Comment by diosceles** [comment]
Justin, there are 34 choices in the actual scenario I am seeing this happen.

**Comment by mrapitis** [comment]
I have copied and pasted the code that was provided but I haven't had any luck reproducing the issue.  Are you certain that the choiceSet1IndexValue is not being modified before the 2nd call to performInteraction?

**Comment by diosceles** [comment]
I have not seen any modification of the Choices vector.  Note that this issue is only reproducible when following step 3 above (selecting a choice).  That is to say, if you render the choices, but then back out or let the interaction time out, you will be able to re-render the choices without incident.  It is not until a choice is selected, and the second attempt to render the interaction is the behavior seen.

**Comment by diosceles** [comment]
Please disregard and close this issue.  I have found the problem.  There was a case when a DeleteChoiceInteraction fired which was not tracked properly.  This caused the code to try and fire an interaction on a choice set which no longer existed.  My apologies for the inconvenience.
