### ISSUE TITLE
Change Layout on PerformInteraction

### ISSUE THREAD

**Issue by diosceles** [smartdevicelink/sdl_android#158]
The proxy method "setdisplaylayout" changes the layout template used on on a "show" command.  However, I am still wondering how to change the layout on an performinteraction. For example, having a performinteraction use the layout "LIST_ONLY".  setdisplaylayout only appears to work for displays of type "show".  What is the API or procedure used to set the layout properly for performinteraction?

**Comment by stefanek22** [comment]
There currently are 5 layouts defined for a given interaction:

ICON_ONLY
ICON_WITH_SEARCH
LIST_ONLY
LIST_WITH_SEARCH
KEYBOARD

Any one of those can be set using layoutMode in PerformInteraction.

**Comment by diosceles** [comment]
@stefanek22 ,

I see that one can set the layoutMode in a PerformInteraction object.  My question however is how one can send this via the call through the SyncProxyALM object.  SyncProxyALM has eight different methods to invoke a performInteraction, however none of them allow for the setting of the layoutMode.  Is there another method in the SyncProxyALM I should be using to send a PerformInteraction object directly?

**Comment by mikeburke106** [comment]
@diosceles It looks like SdlProxyBase and RPCRequestFactory are incomplete for PerformInteraction and several other newer RPC updates.  You will have to create the PerformInteraction object manually to use a specific layout.

**Comment by diosceles** [comment]
So then the solution, at least until SdlProxyBase are complete, would be to create a PerformInteraction object manually.  Since PerformInteraction is derived from RPCRequest, this could then be sent via the SyncProxyALM class via the method "sendRPCRequest"?

**Comment by mrapitis** [comment]
@diosceles Right, you should be able to create the PerformInteraction RPC request manually, populate the desired parameters within the RPC and send the PerformInteraction RPC object with the sendRPCRequest.

**Comment by diosceles** [comment]
This solution appears to work.
