### ISSUE TITLE
Unable to delete choices on PerformInteraction after interaction complete

### ISSUE THREAD

**Issue by diosceles** [smartdevicelink/sdl_android#163]
After doing a PerformInteraction, and the interaction completes, either by timeout or user selection, there are certain scenarios when the choices associated with that interaction need to be deleted and/or reset.

However, when calling deleteInteractionChoiceSet the response callback gives a result code of "IN_USE".  

My assumption was that when the interaction was complete the choices were no longer associated with this interaction.  I could not find any API call to "decouple" the choices from the interaction or otherwise 
"terminate" the interaction.  

What is the proper process if I wanted to create a particular PerformInteraction with a new set of choices?

**Comment by justinjdickow** [comment]
@mrapitis @joeygrover @stefanek22

Any suggestion?

**Comment by mrapitis** [comment]
The only time I have seen IN_USE come back from a deleteInteractionChoiceSet request is when trying to delete an interaction while a PerformInteraction is currently running for the given choiceset, however the concern raised here seems like a different case.  

@diosceles Can you possibly provide steps for us to reliably reproduce this issue?

**Comment by stefanek22** [comment]
This issue was definitely witnessed by some partners in the past.  They had workarounds of waiting at least a few seconds following any interaction that referenced the given choice set before enacting deletion through a sort of garbage collector.  The root cause assumed at the time was that while the interaction was truly finished from the app's point of view, the system / core were still not fully done removing all internal references.

**Comment by justinjdickow** [comment]
@diosceles Do you have any new information regarding this issue? Is this issue with sdl core in github or with a Ford TDK?

**Comment by diosceles** [comment]
To the best of my knowledge this is a sdl core issue.  As stefanek22 mentioned, there was an assumption that the system had not finished removing all references to a choice list after the performInteraction screen was removed.  I myself have not attempted this workaround, however if it is the only solution at the moment I can implement it.  However I would think the proper way this should be handled is that the callback from the deleteChoices should not be invoked until all references are truly cleared.

**Comment by diosceles** [comment]
Confirmed.  New version of software on TDK resolves this issue.  Delete choices are now processed normally.
