### ISSUE TITLE
Develop branch missing some commits from master

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#167]
I'm not sure how this happened, but the develop branch is missing a couple of previous commits from the master branch of the project.  I noticed this issue because I was planning to write another issue for a null pointer exception in convertAppInterfaceUnregisteredReason.

Link to the file in the master branch:
https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/SdlDisconnectedReason.java

Link to the same file in the develop branch:
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/SdlDisconnectedReason.java

It looks like the following two commits never made it in to develop:
https://github.com/smartdevicelink/sdl_android/commit/3028ec4d47e6e7eb8fe0eaa27321d58ef17dda63
https://github.com/smartdevicelink/sdl_android/commit/0f7921545b168dd9e30839900d71a63cc26f79a9

**Comment by joeygrover** [comment]
Fixed with commits

https://github.com/smartdevicelink/sdl_android/commit/e1563e1c2b73f050fd69a075f13e6647f260cb7a
https://github.com/smartdevicelink/sdl_android/commit/47084a842f808436476d0b0a4be62c6cc203a363
