### ISSUE TITLE
Unit Test Framework Change

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_android#173]
Relevant classes [on feature/unit_tests branch]:
_com/smartdevicelink/test/proxy/SdlProxyConfigurationResourcesTests_
_com/smartdevicelink/test/proxy/SdlProxyBaseTests_
_com/smartdevicelink/test/proxy/SdlProxyALMTests_
_sdl_android_tests Manifest_

In order to test any of the aforementioned, a context value is needed, which is Android specific. Currently testing uses the JUnit TestCase framework. These classes need the [AndroidTestCase](http://developer.android.com/reference/android/test/AndroidTestCase.html) framework to run, which is an extension of the JUnit TestCase framework, but is run differently in Eclipse. Intermingling types of tests will mean that each test must be run singly, because if run using either JUnit Test basis or the Android JUnit Test basis in bulk testing they will throw errors and stop all tests from being run. All existing tests should still work if the class extension is changed, so my proposal is to shift the framework. junit.framework.TestCase  ->  android.test.AndroidTestCase

I am unaware of any issues with making this shift but maybe there is some reasoning I missed @mikeburke106?

Related : 5be2e455adaa648c0630082e3fd784669f579605

**Comment by mikeburke106** [comment]
This sounds like eclipse being finicky, which I'm not sure is a good reason to modify the existing test cases.  Like you say, AndroidTestCase is an extension of the JUnit TestCase, so the tests should be able to run as-is.

The bigger problem is that these classes you mention are not testable due to their implementation.  For example, there's no way to validate data being "sent through" or "received from" the proxy as it is written (or to test the ridiculous logic in the 1,200 line [handleRPCMessage method](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java#L1450-2606), for that matter).  There's going to have to be some pretty serious overhaul in order to properly test these classes.

**Comment by MikaylaRay44** [comment]
Do you mean that I _should_ be able to run both kinds of tests simultaneously without conflicts?

Regardless it looks like AndroidTestCase won't work as I hoped, I ran into [this](http://stackoverflow.com/questions/10172636/unable-to-find-instrumentation-target-package-com-xyz) issue, but haven't spent enough time looking into it to see if I can get around it.

I am not sure if this is an implementation problem either, unless the library project was never intended to handle instance-specific values. For example, a context object is needed in SdlProxyConfigurationResourcesTests to check against a valid TelephonyManager parameter. You can see the not commented-out version of the test [here](2c6b7de3e9c68aa86f7da40b7d618e84b231618a). Now, that hasn't been tested because of the aforementioned instrumentation issue I have been running into, but it is rather simple and much like other unit tests.

I have not touched much upon SdlProxyBase class yet, but I do know that it handles (at least) two separate instances of a Server object that is provided by the user. In the [SdlProxyALMTests](sdl_android/sdl_android_tests/src/com/smartdevicelink/test/proxy/SdlProxyALMTests.java) it is passing up a Service object as a parameter (in some of it's 25 constructors) to the SdlProxyBase class. If I test these as null, then an exception is thrown and I am unable to test the assignment of the other parameters. However, I cannot seem to get a mock service object to work either. There is a more extensive list at the top of the class of issues that I have yet to work out and which tests they affect.

Also, yes I have run into the issue of not being able to test any of the data for the code that would be sent or returned from the proxy, the RegisterAppInterface return value methods for example (also in SdlProxyALMTests), but I'm not sure what kind of an overhaul would need to be done to get around that issue. Getting the test application project to connect to an emulator to have a dummy project send some data through for testing seems a bit of an extreme measure for just a few tests, which I'm not even certain are possible through that means either.
