### ISSUE TITLE
SendLocation ClassCastException From JSON Value

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_android#181]
> com/smartdevicelink/proxy/rpc/SendLocation

While I was writing the unit tests for the SendLocation class a ClassCastException from a getter method was revealed on one of the three calls made to test it.

The first test on the getLatitudeDegrees method, which returns a Float, was the null value test and it passes.
```java
SendLocation msg = new SendLocation();
assertNotNull("Null object creation failed.", msg);
assertNull("Latitude wasn't set, but getter method returned an object.", msg.getLatitudeDegrees());
```
> Results:
> Latitude Float Type Test: false
> Latitude Integer Type Test: false
> Latitude Double Type Test: false
> Latitude Object Type Test: false
> Latitude Null Value Test: true

The second test was the manual value test through setLatitudeDegrees, and it passes this also.
```java
SendLocation msg = new SendLocation();
msg.setLatitudeDegrees(42f);
assertEquals("Latitude didn't match input latitude.", 42f, msg.getLatitudeDegrees());
```
> Results:
> Latitude Float Type Test: true
> Latitude Integer Type Test: false
> Latitude Double Type Test: false
> Latitude Object Type Test: true
> Latitude Null Value Test: false

However, it fails on the third test, where the value is pulled from the JSON RPC test files.
```java
// Other json code ...
JSONObject parameters = JsonUtils.readJsonObjectFromJsonObject(body, RPCMessage.KEY_PARAMETERS);
assertEquals("Latitude doesn't match input latitude.", JsonUtils.readDoubleFromJsonObject(parameters, SendLocation.KEY_LAT_DEGREES).floatValue(), 42f);
```
> Results:
> Latitude Float Type Test: false
> Latitude Integer Type Test: false
> Latitude Double Type Test: true
> Latitude Object Type Test: true
> Latitude Null Value Test: false

As you can see the type that is being read in is viewed as a double, because JSON does not have any specific format for handling floats and views all numbers with decimals as doubles.

```java
public Float getLatitudeDegrees(){    	
    return (Float) parameters.get(KEY_LAT_DEGREES);
}
```

The ClassCastException occurs because you cannot cast the type Double to a Float. A solution to this issue, if the value is read from the JSON file as a Double or Integer, to use the wrapper classes .floatValue() method.

```java
public Float getLatitudeDegrees(){    	
    if (parameters.get(KEY_LAT_DEGREES) instanceof Integer) {
    	return ((Integer)parameters.get(KEY_LAT_DEGREES)).floatValue();
    } else if (parameters.get(KEY_LAT_DEGREES) instanceof Double) {
    	return ((Double) parameters.get(KEY_LAT_DEGREES)).floatValue();
    } else {
    	return (Float) parameters.get(KEY_LAT_DEGREES);
    }
}
```

This is also a problem in getLongitudeDegrees() in the same class.

**Comment by mrapitis** [comment]
We actually have implemented all floats from the mobile api spec as doubles in the mobile library.  I would recommend changing all float types used by send location as doubles to be consistent with the rest of the project.

**Comment by MikaylaRay44** [comment]
Alright, that would make sense as I have not seen floating point numbers used anywhere else. Should I keep the Float methods as legacy code or replace them entirely?

**Comment by mrapitis** [comment]
Not sure if there are any objections but, I think replacing the methods entirely would be sufficient.

**Comment by MikaylaRay44** [comment]
Alright, the pull request has been updated to reflect that.
