### ISSUE TITLE
Control service is declared as Heartbeat service in SessionType.java

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_android#183]
"Heartbeat" needs to change to "CONTROL". (As a side note these static finals need to conform to correct naming conventions of all caps)

See:  
https://github.com/smartdevicelink/sdl_android/blob/feature/remote_control/sdl_android_lib/src/com/smartdevicelink/protocol/enums/SessionType.java#L16

**Comment by MikaylaRay44** [comment]
This has been changed in develop and naming changes have also been proposed in the refactor branch. Should this be closed, or remain open until the naming change is also accepted?

**Comment by joeygrover** [comment]
Should have already been closed.
