### ISSUE TITLE
Need to confirm that proxy responds appropriately to a message coming over the hybrid service

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_android#184]
An [issue](https://github.com/smartdevicelink/sdl_core/issues/110) was raised that the service type for all messages coming from sdl core default to the RPC service and were never changed, even if the rpc message contained binary data.

A [pull request](https://github.com/smartdevicelink/sdl_core/pull/111) fixes this issue but validation of the proxy still needs to occur before it is merged.

**Comment by justinjdickow** [comment]
See iOS issue: https://github.com/smartdevicelink/sdl_ios/issues/194

**Comment by joeygrover** [comment]
Confirmed.
