### ISSUE TITLE
TouchEvent Spec Naming

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_android#213]
> _com/smartdevicelink/proxy/rpc/TouchEvent_

The naming of several methods and key variables in the [TouchEvent](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/TouchEvent.java) class has been oversimplified and become rather unclear in purpose .

```java
public static final String KEY_TS = "ts";
public static final String KEY_C = "c";

public List<Long> getTs() { ... }
public void setTs(List<Long> ts) { ... }
    
public List<TouchCoord> getC() { ... } 
public void setC( List<TouchCoord> c ) { ... }
```

What do `ts` and `c` stand for? It is very difficult to tell ***just*** by looking at the method naming that `c` implies a list of [TouchCoord](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/TouchCoord.java) values and that `ts` implies a millisecond timestamp value represented as a list of long types converted from integer types.

This naming is also present in the mobile spec sheet, which points to an even deeper rooted issue.

```xml
<struct name="TouchEvent">
...
<param name="ts" type="Integer" mandatory="true" array="true" minvalue="0" maxvalue="2147483647" minsize="1" maxsize="1000">
<param name="c" type="TouchCoord" mandatory="true" array="true" minsize="1" maxsize="1000">
```

Once these methods are documented that will help considerably, however, it is not intuitive to use getter and setter methods that are not named clearly and according to what they get or set. Changing these values will improve code readability.

**Comment by justinjdickow** [comment]
The methods will be deprecated and use `timestamp` and `coordinates`

**Comment by tpulatha** [comment]
Just so people understand. The reason to use "ts" and "c" in the mobile_api are that we send a large number of touchEvents. Therefore we try to save bandwidth on the transport layer and use shorter names as these get transmitted in the JSON.

**Comment by joeygrover** [comment]
PR #304 was merged into develop and solves this issue
