### ISSUE TITLE
Proper Logging

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_android#217]
As a follow up to a post merge #190 develop branch, the project should be cleaned up to include logging where appropriate. Uses of the various logging levels can be seen in the chart on the above pull request. Also as a part of this, the intention of trace logging should be more clearly defined and used accordingly.

This is especially crucial for #221 to involve non-encoded trace log messages.

**Comment by justinjdickow** [comment]
Everyone should keep in mind that when they update files or make enhancements that they can use the logging classes and the appropriate log levels to give developers additional information
