### ISSUE TITLE
What is SDL_LIB_TRACE_KEY used for in SDLProxyBase?

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_android#218]
The final string value `SDL_LIB_TRACE_KEY` is used in the [SdlProxyBase](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyBase.java) class solely as a parameter for sending information to the [SdlTrace](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/trace/SdlTrace.java) class, which also contains an identical value. These two keys are compared against, but my question is _why would they ever be different?_

The token is never used in the message that is logged and both are hardcoded values.

I believe this is related to the decode key mentioned in discussion concerning #220.

**Comment by justinjdickow** [comment]
The logProxyEvent method is a public method, so only a class that has that key can use the method. I'll reopen a different issue to remove the key from the public library
