### ISSUE TITLE
PNG transparency not being respected in Choice object

### ISSUE THREAD

**Issue by diosceles** [smartdevicelink/sdl_android#232]
When setting the image value on a Choice object, it does not appear as if the transparency color is respected when a performInteraction is invoked with the given Choice.  The image in question has a black rectangular background instead of a transparency.

The image is set with:
```java
Image image = new Image();
image.setImageType(ImageType.DYNAMIC);
image.setValue(FAVORITE_ICON);
choice.setImage(image);
```
Where FAVORITE_ICON is the image loaded via a putFile call. 

That code is:
```java
byte[] buffer = getBitmapFromResource(this, R.drawable.heart_highlight);
mProxyALM.putfile(FAVORITE_ICON, FileType.GRAPHIC_PNG, false, buffer, autoIncCorrId++);
```
The "heart_highlight" is a PNG file within my Android project.

**Comment by joeygrover** [comment]
Can you share the getBitmapFromResource function?

**Comment by diosceles** [comment]
Yes sorry, that's a simple reference to an Android function:

 public byte[] getBitmapFromResource(Context myParent, int id) {
        Bitmap bm = BitmapFactory.decodeResource(myParent.getResources(), id);
        return getBytesFromBitmap(bm);
    }

**Comment by joeygrover** [comment]
You could try two things:

The Android Bitmap class has a setter for alpha so you can try to set that before you grab the bytes from the bitmap:
````Java
 public byte[] getBitmapFromResource(Context myParent, int id) {
        Bitmap bm = BitmapFactory.decodeResource(myParent.getResources(), id);
        bm.setAlpha(true);
       return getBytesFromBitmap(bm);
}
````
Or, you could try to simply send the raw bytes without converting it to a Bitmap first:
````Java
	private byte[] contentsOfResource(Context context, int resource) {
		InputStream is = null;
		try {
			is = context.getResources().openRawResource(resource);
			
			ByteArrayOutputStream os = new ByteArrayOutputStream(is.available());
			final int buffersize = 4096;
			final byte[] buffer = new byte[buffersize];
			int available = 0;
			while ((available = is.read(buffer)) >= 0) {
				os.write(buffer, 0, available);
			}
			return os.toByteArray();
		} catch (IOException e) {
			Log.w(TAG "Can't read icon file", e);
			return null;
		} finally {
			if (is != null) {
				try {
					is.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
	}
````

**Comment by diosceles** [comment]
The first proposed solution of adding alpha channel does not work.  However, the second solution of sending raw bytes succeeded.  Seems like using the second method shown is the way to resolve this.

**Comment by joeygrover** [comment]
Good to hear! I believe in the future this code block will probably be moved into the library for convenience.
