### ISSUE TITLE
Update setVersion method in WiProProtocol class

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#234]
We need to update the setVersion method in the WiProProtocol class as it currently has a hard coded value of 2 when the protocol version is anything greater than 1.  Please see the code linked here:

https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java#L56

To maintain future compatibility, we need to update the method for v3 support.

Sample method update to maintain future compatibility:
```
public void setVersion(byte version) {
		this._version = version;
		if (version > 3) {
			this._version = 3;
			HEADER_SIZE = 12;
			MAX_DATA_SIZE = MTU_SIZE - HEADER_SIZE;
			_headerBuf = new byte[HEADER_SIZE];
		} else if (version > 1) {
			this._version = version;
			HEADER_SIZE = 12;
			MAX_DATA_SIZE = MTU_SIZE - HEADER_SIZE;
			_headerBuf = new byte[HEADER_SIZE];
		} else if (version == 1){
			HEADER_SIZE = 8;
			MAX_DATA_SIZE = MTU_SIZE - HEADER_SIZE;
			_headerBuf = new byte[HEADER_SIZE];			
		}		
	}
```

**Comment by joeygrover** [comment]
Fixed with pull request #246
