### ISSUE TITLE
Issues with offline pull request

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_android#238]
From comment on #174 A copy paste error exists in RPCRequestFactory here:

https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/RPCRequestFactory.java#L321

The other issue is that the logic in the robust parameter checking assumes that we would never send an empty array across as a parameter as seen in multiple places, for example:

https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/AlertManeuver.java#L124
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/AlertManeuver.java#L201

https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/AddCommand.java#L189

https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/Alert.java#L388

https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/Choice.java#L147

An empty array as a parameter is not necessarily invalid data, this is especially true for the case of softbuttons where an empty array of softbuttons indicates to core that the existing onscreen softbuttons for this particular rpc should be cleared (hence this commit prevents the clearing of softbuttons).

If possible, I suggest we revert this commit and submit a new revised pr. If we cannot revert, we will need to submit a new pr with fixes as a higher priority.

thanks

**Comment by joeygrover** [comment]
@mrapitis I think the best corse of action would be to revert the merge. After looking at the code, I support the idea of better parameter checking but some of the logic in the original pull request doesn't seem to make sense. I'd say we rethink how we want to handle this. Sound good?

**Comment by mrapitis** [comment]
@joeygrover sounds like a good plan.  I have a local branch that has the commit reverted, if it makes things easier I can submit a pull request.  
thanks

**Comment by joeygrover** [comment]
Fixed with merge #239
