### ISSUE TITLE
RPC classes should have constructors

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#24]
RPC classes have been designed to have empty constructors:

```java
public AddCommand() {
    super("AddCommand");
}
```

The only way for developers to set information within an RPC class is to create an empty object and add information using setter methods.  For example, to initialize an AddCommand, a developer currently has to do this:

```java
AddCommand item = new AddCommand();
item.setCmdID(100);

Vector<String> vrCommands = new Vector<String>();
vrCommands.add("item");
item.setVrCommands(vrCommands);

Image icon = new Image();
icon.setValue("icon.png");
icon.setImageType(ImageType.DYNAMIC);
item.setCmdIcon(icon);

MenuParams params = new MenuParams();
params.setParentID(1000);
params.setPosition(0);
params.setMenuName("item");
item.setMenuParams(params);
```

If all RPCs define proper constructors, the above code could be reduced to something like this:

```java
AddCommand item = new AddCommand(100, new MenuParams(1000, 0, "item"),
  new Image("icon.png", ImageType.DYNAMIC), Arrays.asList(new String[]{"item"}));
```

This saves developers 12 lines of code for a single AddCommand object.

In my [**feature/refactor_rpcs**](http://git.projects.genivi.org/?p=smartdevicelink_android.git;a=shortlog;h=refs/heads/feature/refactor_rpcs) branch on GENIVI, I have defined constructors in the newly designed RPC classes, which can be used for reference.

**Comment by justinjdickow** [comment]
Covered under #20
