### ISSUE TITLE
Update proxy to track both incoming and outgoing heartbeats

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#243]
The proxy needs to be updated to keep track of when a heartbeat request is received from the module and provide a corresponding ACK back.  In addition the proxy should keep track of when a heartbeat request is sent to the module and its corresponding ACK.  In both cases, if a response is not received within the specified timeout, a heartbeat timeout should occur.

**Comment by justinjdickow** [comment]
@mrapitis Does "heartbeat timeout" mean anything other than disconnecting the proxy and notifying the developer?

**Comment by mrapitis** [comment]
@justinjdickow That is its entire purpose.
