### ISSUE TITLE
Do I need to sign a release agreement with Ford?

### ISSUE THREAD

**Issue by sangyuruo** [smartdevicelink/sdl_android#255]
I developed an app using sdl-android libs , Do I need to sign a release agreement with Ford?
thanks!

**Comment by joeygrover** [comment]
Hey @mrapitis can you help provide a better answer to this? I'm assuming short answer is to work with Ford vehicles there is an agreement to be signed through [Ford's developer site](https://developer.ford.com/).

**Comment by mrapitis** [comment]
@sangyuruo Yes, please create an account on the [Ford's developer site] (https://developer.ford.com/ ) if you have not done so already and after logging in click on the 'Distribute' button.  From there you should see a link to a form that will allow you to begin the request to distribute process.

**Comment by justinjdickow** [comment]
@sangyuruo Can you please let us know if this answers your question so we can close out the issue?
