### ISSUE TITLE
Simplify process of creating SdlProxyALM object

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#256]
We currently have 26 different constructors to create a SdlProxyALM object... it can be very difficult for a developer to know which constructor to utilize and what parameters should be passed in.  By providing a builder for developers we can simplify the process of creating a sdl proxy object, this will also lower our overall maintenance of the SdlProxyALM class

**Comment by huaguoping** [comment]
For adding USB support, what parameters should be passed in? I have already make the following changs to AndroidManifest.xml:
    
    1. add these lines to <manifest>…</manifest>:
      
      <uses-feature android:name="android.hardware.usb.accessory"/>
    
    2. add these lines to <application>…</application>:
     <activity android:name="com.smartdevicelink.transport.USBAccessoryAttachmentActivity">
         <intent-filter>
            <action android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED"/>
         </intent-filter>
         <meta-data
            android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED"
            android:resource="@xml/accessory_filter"/>
     </activity>
 
    3. set minimum SDK version to 12:
     <uses-sdk android:minSdkVersion="12"/>
 
And, some changes to xml/accessory_filter:

     <?xml version="1.0" encoding="utf-8"?>

     <resources>
          <usb-accessory model="HMI" manufacturer="Ford" version="1.0"/>
     </resources> 

Now, I try "new USBTransportConfig(getApplicationContext())" to construct the USBTransportConfig.
But, it seems not work.... :( 
Before I try this, I got the error "libusb_open failed" on the terminal.And now, I do not see any log on the terminal after I choose the USB and press the OK button on my Android phone.  What is the significant thing I have missed? Is the parameter wrong? I use the following parameter:

     result=new SdlProxyALM((IProxyListenerALM)this, null, appName, null, null, null,
    IS_MEDIA_APP, null, DEFAULT_LEAGUAGE, DEFAULT_LEAGUAGE, APP_ID, null, false, false,  new USBTransportConfig(getApplicationContext()));

Could you help me ? What parameters should be passed in SdlProxyALM?

**Comment by ojmakke** [comment]
Regarding you issue the log file, you may want to check the Debugging Considerations in:
https://developer.android.com/guide/topics/connectivity/usb/index.html

That will help shed the light on why it seems not to work.

**Comment by alangonzalez** [comment]
SdlProxyALM for iOS was setup differently with a few required parameters and then all optional args objecxt which you would create ahead of time and send in to the constructor.  This leaves the constructor simple for simple apps, but adds ability to use other setups when necessary.

**Comment by joeygrover** [comment]
Closing issue, original issue fixed with pull request #257 .
