### ISSUE TITLE
Release is missing getter for HMICapabilities

### ISSUE THREAD

**Issue by fkattner** [smartdevicelink/sdl_android#276]
Current release of the Android lib does not provide a getter for the HMICapabilities e.g. proxy.getHmiCapabilities().

Needed for OnlineTraffic feature.

**Comment by joeygrover** [comment]
Including into develop branch. It will be included in next release. See [here](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/SdlProxyALM.java#L1410).
