### ISSUE TITLE
Improve RPC commands architecture

### ISSUE THREAD

**Issue by ChernyshovYuriy** [smartdevicelink/sdl_android#277]
Hi there,

There is a huge copy / paste functionality in the "com.smartdevicelink.proxy.rpc" package.
In every command there is the same code, more / less getting and setting parameters to / from Map.
How you guys didn't see it?
I suggest to set few helper methods (probably 5 or 10) in some common class, and then in each concrete command just invoke this method and pass key only.
In this case each command will look much more clearly for the other developers. Easy to extend and modify.

**Comment by joeygrover** [comment]
Fixed with #536
