### ISSUE TITLE
WiperStatus  definition

### ISSUE THREAD

**Issue by parametersky** [smartdevicelink/sdl_android#278]
can anyone explain the definition in the WiperStatus.java below?        
        OFF,
        AUTO_OFF,
	OFF_MOVING,
	MAN_INT_OFF,
	MAN_INT_ON,
	MAN_LOW,
	MAN_HIGH,
	MAN_FLICK,
	WASH,
	AUTO_LOW,
	AUTO_HIGH,
	COURTESYWIPE,
	AUTO_ADJUST,
	STALLED,
	NO_DATA_EXISTS;

**Comment by joeygrover** [comment]
Should be taken care of with #250 now merged. See the updated [WiperStatus.java](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/WiperStatus.java)
