### ISSUE TITLE
Register Steering Wheel Button

### ISSUE THREAD

**Issue by NDNELSON** [smartdevicelink/sdl_android#287]
Hello Could anyone help me please? I have tried how to suscribe a physical button or steering wheel button Push-To-Talk. I would like to get the long press event of this button to start my own service

I have tried it in this way:
proxy.subscribeButton(ButtonName.valueForString("Push-To-Talk"), nextCorrelationID());
and:

proxy.subscribeButton(ButtonName.PTT), nextCorrelationID());

but it doesnt work or can not resolve symbol in android

**Comment by asm09fsu** [comment]
@NDNELSON SDL does not provide support for override of the VR (Push to talk) button

**Comment by NDNELSON** [comment]
OK thank you. I didnt know that because th ford app link documentation at ford developers says yes.

**Comment by asm09fsu** [comment]
@NDNELSON would you be able to point me to that documentation?

**Comment by asm09fsu** [comment]
@NDNELSON also, please reference [here](https://github.com/smartdevicelink/sdl_android/blob/e5e79617a59d99cff1aee5773fa181101a9451d2/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/enums/ButtonName.java) for all possible ButtonName values.

**Comment by NDNELSON** [comment]
I read it in this link https://developer.ford.com/pages/getting-started in the Human Machine Interface (HMI)  part

**Comment by joeygrover** [comment]
It seems the referenced documentation might have been a little misleading. The button itself does not currently have the ability to be overridden through the SDL API's. Its functionality is exposed through SDL by allowing an app the ability to leverage the onboard voice recognition.

**Comment by NDNELSON** [comment]
Ok thank you a lot. I have another doubt

Excuse me I am new in developing with applink. I am developing and music
app, I am using the sdl or applink library version 4.0.

I have a huge doubt. I want to show a list of artist,albums or song
depending the softbutton or command choiced by the user. I am trying to
show this in this way:

After the user choices the command for example Artitst, I use deletecommand
to clear all commands and then innmediatly addcommand to add each elements
of my list. But it doesnt work I get the main screen in hmi_full instead
the List with the elements I want, even in some commands I get a generic
error response . I also tried with onadsubmenu but I get the same generic
error and I dont want submenu because when the user is driving the system
doesnt let to interact with submenu by screen.

I want to develop an app like spotify menu to choice music.
Could anyone hel me please? I hope I dont upset to you. thank you for your
support

2016-02-08 12:50 GMT-06:00 Joey Grover <notifications@github.com>:
