### ISSUE TITLE
Show List of music in hmi

### ISSUE THREAD

**Issue by NDNELSON** [smartdevicelink/sdl_android#288]
Excuse me I am new in developing with applink. I am developing and music app, I am using the sdl or applink library version 4.0.

I have a huge doubt. I want to show a list of artist,albums or song depending the softbutton or command choiced by the user. I am trying to show this in this way:

After the user choices the command  for example Artitst, I use deletecommand to clear all commands and then innmediatly addcommand to add each elements of my list. But it doesnt work I get the main screen in hmi_full instead the List with the elements I want, even in some commands I get a generic error response .  I also tried with onadsubmenu but I get the same generic error and I dont want submenu because when the user is driving the system doesnt let to interact with submenu by screen.

I want to develop an app like spotify menu to choice music.
Could anyone hel me please? I hope I dont upset to you. thank you for your support

**Comment by duanjj0929** [comment]
I think you may try with CreateInteractionChoiceSet/PerformInteraction/DeleteInteractionChoiceSet.

**Comment by joeygrover** [comment]
This is an integration issue, not an issue with the library. For future reference please join the SmartDeviceLink slack channel for support on such issues. Join here: [![Slack Status](http://sdlslack.herokuapp.com/badge.svg)](http://slack.smartdevicelink.com)
