### ISSUE TITLE
SoftButtons not appear in show request

### ISSUE THREAD

**Issue by NDNELSON** [smartdevicelink/sdl_android#295]
Hello everybody I am developing a music app with the library sdl 4.0 

I can get all my softbuttons in alert rpc but not in show or scrollable message here is my code even i try to use  SetDisplayLayout Requets but i get an Invalid Data response. My tdk is an ford fiesta 2016with sync 3 and LCD 8" screen.
       
And here are my avaliable templates that I Get from the tdk Templates:﹕ [GRAPHIC_WITH_TEXT, TEXT_WITH_GRAPHIC, TILES_ONLY, GRAPHIC_WITH_TILES, TILES_WITH_GRAPHIC, GRAPHIC_WITH_TEXT_AND_SOFTBUTTONS, TEXT_AND_SOFTBUTTONS_WITH_GRAPHIC, GRAPHIC_WITH_TEXTBUTTONS, DOUBLE_GRAPHIC_WITH_SOFTBUTTONS, TEXTBUTTONS_WITH_GRAPHIC, TEXTBUTTONS_ONLY, LARGE_GRAPHIC_WITH_SOFTBUTTONS, LARGE_GRAPHIC_ONLY]

Here is my code: 
    SetDisplayLayout layoutRequest = new SetDisplayLayout();
            layoutRequest.setDisplayLayout("TEXT_AND_SOFTBUTTONS_WITH_GRAPHIC");
            layoutRequest.setCorrelationID(nextCorrelationID());
            proxy.sendRPCRequest(layoutRequest); // Here I get an Invalid Data Form SetDisplayLayout       Response
            proxy.show("Text1","Text 2 ","Text3","Text    4",null,null,null,appImage,setUpSoftButtons(SoftButtons.PRINCIPAL1),null,TextAlignment.LEFT_ALIGNED,nextCorrelationID()); // Here I get a show response succes but I can´t see my softbutton in the screen

**Comment by parametersky** [comment]
how did you build your softbutton? can you show the code?

**Comment by KennyLv** [comment]
I've got same problem :


                                List<SoftButton> softButtons = new ArrayList<>();
                                SoftButton btn_1 = new SoftButton();
                                btn_1.setType(SoftButtonType.SBT_TEXT);
                                btn_1.setText("Button1");
                                softButtons.add(btn_1);
                                SoftButton btn_2 = new SoftButton();
                                btn_2.setType(SoftButtonType.SBT_TEXT);
                                btn_2.setText("Button1");
                                softButtons.add(btn_2);
                                SoftButton btn_3 = new SoftButton();
                                btn_3.setType(SoftButtonType.SBT_TEXT);
                                btn_3.setText("Button1");
                                softButtons.add(btn_3);

                                Show showRequest = new Show();
                                showRequest.setSoftButtons(softButtons);
                                showRequest.setCorrelationID(CorrelationIdGenerator.generateId());
                                showRequest.setOnRPCResponseListener(new OnRPCResponseListener() {
                                    @Override
                                    public void onResponse(int correlationId, RPCResponse response) {
                                        if (((ShowResponse) response).getSuccess()) {
                                            Log.i("SdlService", "SoftButton Successfully showed.");
                                        } else {
                                            Log.i("SdlService", "SoftButton Show request was rejected.");
                                        }
                                    }
                                });
                                proxy.sendRPCRequest(showRequest);
