### ISSUE TITLE
Remove HelloSdl from library project

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#309]
Currently we are including the multiplexed version of the HelloSdl project in the develop branch of the proxy library project.  Ideally we would want to just update the HelloSdl project to include an additional branch that includes multiplexing and remove the sample from the proxy library.

**Comment by joeygrover** [comment]
The dev branch of HelloSdl project should be updated to the dev version of the library

**Comment by mrapitis** [comment]
Cool, could we remove the reference in the library?

**Comment by joeygrover** [comment]
Once the HelloSdl project is updated I can create fix for the library.

**Comment by mrapitis** [comment]
Sounds good.

**Comment by joeygrover** [comment]
Fixed with PR #318
