### ISSUE TITLE
Use of hard-coded strings instead of SDK defined constants

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#310]
I have noticed in a couple places that there are hard-coded strings being used instead of the constants already defined by the Android SDK.  I haven't been looking for this type of usage but the two places I have seen it are in:

- com.smartdevicelink.transport.SdlBroadcastReceiver.java around line 180:
`ActivityManager manager = (ActivityManager) context.getSystemService("activity");`
should be:
`ActivityManager manager = (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);`
- com.smartdevicelink.transport.TransportBroker.java around line 400, same as above.

**Comment by joeygrover** [comment]
PR #314 was merged into develop which resolves this issue.
