### ISSUE TITLE
SdlProxyALM method signatures changed without deprecation

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#313]
Some signatures for SdlProxyALM have changed in our develop branch to require a context and the methods default to the MultiplexTransport.  Would be good practice for us to deprecate the old methods and still provide the Bluetooth transport for those methods while including the new methods that also utilize the multiplexed transport.  Overall it would be good to try to get away from the constructor model because of its high maintenance.

**Comment by joeygrover** [comment]
Can you catalog the instances? And why don't we just deprecate all the constructors for the next release?

**Comment by mrapitis** [comment]
Sounds good, maybe we can plan to deprecate all. I will update the initial task with a list of instances.

**Comment by joeygrover** [comment]
I believe [this is the commit](https://github.com/smartdevicelink/sdl_android/commit/3d8bb3ee5507e1743bf9afb1dbd5c88bf066b845#diff-9ef7f934d73df733554e4e8bb1336df0L45) where it happened so I can probably just go through these.

**Comment by mrapitis** [comment]
Right... that's probably the easiest way.  Also the team created a doc that includes a list for (hopefully) quick reference.
[SDLProxyALM changes.pdf](https://github.com/smartdevicelink/sdl_android/files/342046/SDLProxyALM.changes.pdf)
