### ISSUE TITLE
PutFile request (and others) being lost in a series of requests 

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#327]
We have a test app that sends several requests triggered by receiving an HMI_FULL status.  The series of requests include 7 PutFile and 2 CreateIntereactionChoice requests, among others.  If the requests are sent in a certain way then the app does not get a response for the last PutFile request or the first CreateInteractionChoice request.  The requests go like this:

1. Check/set language
2. Get display capabilities
3. Seven PutFile requests
4. SetGlobalProperties request
5. Two CreateInteractionChoiceSet requests
6. ListFiles request
7. Ten SubscribeButton requests
8. AddSubMenu request
9. Thirteen AddCommand requests

What happens is that there is no response for the seventh PutFile or first CreateInteractionChoiceSet requests.

We've debugged SDLCore and apparently there is at least one message being tossed as garbled by the lower level code before it even gets converted from bytes.  We're not sure if this message is one of the two missing ones described above or some other message.

I'm attaching the modified SdlService class from the HelloSdl sample that exhibits this behavior and a capture of logcat messages that show the order of requests and responses.

[lostrequests.zip](https://github.com/smartdevicelink/sdl_android/files/423288/lostrequests.zip)

**Comment by madhuy** [comment]
SDL core logs says
 “Drop ill-formed message from mobile, partially parsed: (ProtocolPayloadV2  header: (ProtocolPayloadHeaderV2  rpc_type: kRpcTypeRequest, rpc_function_id: 78438248, correlation_id: 2921744882, json_size: 1291890886), json (bytes): 0, data (bytes): 0)"

**Comment by joeygrover** [comment]
What version of core are you using? We tested with the latest from the master branch and we are not seeing the issue.

**Comment by jthrun** [comment]
@madhuy says we are using the latest from master.  I was able to repro with the TDK as well, not that it has the latest anything.

**Comment by joeygrover** [comment]
@BTPankow can you comment?

**Comment by BTPankow** [comment]
Our test was with the latest master using bluetooth.  I've attached logs from the test showing that all requests were responded to with a SUCCESS (android_requests.log) and showing sdl_core processing (sdl_core_requests.log).

There were quite a few changes in master with the commit of 4.1.0 changes recently, so this could make a difference if the changes haven't been pulled yet.

[putfile_logs.zip](https://github.com/smartdevicelink/sdl_android/files/450589/putfile_logs.zip)

**Comment by jthrun** [comment]
We did not notice there was a new commit only a couple days ago.  We will merge that and retest.

**Comment by jthrun** [comment]
I am not able to repro this with the latest from the master branch.  I want our tester to verify, then I will close this ticket.

**Comment by jthrun** [comment]
Seems that latest from master (4.1.0 merge) has fixed this issue.
