### ISSUE TITLE
Protocol bug fixes and memory leak

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#333]
The protocol and message frame assembler is leaking memory when control frames are being processed. 
handleControlFrame never removes the message from the _assemblerForMessageID hashtable after processing (handleSingleFrameMessageFrame and notifyIfFinished both clean up the hashtable).

Please see link below to review handleControlFrame
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/protocol/WiProProtocol.java#L360

 We also have a couple of places where signed vs unsigned values are being compared resulting in a failure in a test for equality.  Pull request to follow with a commit resolving both problems.

**Comment by joeygrover** [comment]
Merged into develop. Will be included in next release.
