### ISSUE TITLE
When proxy is cycled app does not reconnect to running router

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#335]
This issue is identical to https://github.com/smartdevicelink/sdl_android/issues/328 except that it happens when the proxy is cycled rather than when the app is restarted.  I first tried modifying the way the proxy service handled onProxyClosed() call but it did not resolve the issue.  I tried modifying the SdlBroadcastReceiver and this fixed the issue.

This one is block our testing of certain functionality in the HU such as changing languages; also when something bad happens like when some exception occurs such as https://github.com/smartdevicelink/sdl_android/issues/332.

Here is the existing code:

https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L194-L198

```java
	private static boolean isRouterServiceRunning(Context context, boolean pingService){
		...

	    		return true;
	        }
	    }
		
		return false;
		
	}
```

Here is my change to that code:

```java
	private static boolean isRouterServiceRunning(Context context, boolean pingService){
		...

//	    		return true;
	        }
	    }
		
//		return false;
	        return runningBluetoothServicePackage.size() > 0;
	}
```

**Comment by joeygrover** [comment]
Yup that logic makes sense. Looks like I was trying to optimize to only run through as long as needed, but since that's where the list is populate it wasn't becoming a full list. Hotfix PR will be coming.
