### ISSUE TITLE
SDL BT channel given to another socket after client connect

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#338]
The issue is that there is a BT server socket open on channel X which then accepts a client connection and is closed.  Following this another server socket is opened and the Android system gives this new socket the same channel X which is already being used by the connection opened with the previously closed server socket.  As a result, the new server socket is never able to be connected to.

The work-around is to not close the first server socket after it accepts its connection, leaving it open so that the OS can not assign the same channel to the new server socket.

This OS issue seems to affect certain Android versions/devices, not all of them.  We have reports of this issue in the scenario where our SDL app, which has a connection to the HU, tries to launch a navigation app.  The navi app opens (a non-SDL) BT socket to connect with the HU but the HU can't connect to that server socket because the channel is already in use by SDL.

We have some minimal logs from the partner in one case, from their HU:

```
Line 3085: 12-31 21:40:09.930 I/btlib ( 126): [APP]: BT_GEN_SERVICE_SEARCH_EXT_IND serviceChannel=0x05 serviceNameLen=0x11 serviceName=[App Suite]
Line 3734: 12-31 21:40:15.280 I/btlib ( 126): [APP]: BT_GEN_SERVICE_SEARCH_EXT_IND serviceChannel=0x06 serviceNameLen=0x0A serviceName=[SdlRouter]
Line 6256: 12-31 21:40:31.490 I/btlib ( 126): [APP]: BT_GEN_SERVICE_SEARCH_EXT_IND serviceChannel=0x06 serviceNameLen=0x12 serviceName=[Multimedia]
```

Note that the the second and third connections are on the same channel, in this case channel 6.

This seems to affect certain Samsung devices, the partner is using Samsung Galaxy Edge with 6.0.1 and Galaxy Note 4 with both 6.0.1 and 5.0.1.

The scenario is:
- App Suite (companion app) has a BT connection
- App Suite also has and SDL Router running with a connection
- Multimedia app (non-SDL) is launched and opens BT socket but HU can't connect since app's server socket has been assigned the same channel as the SDL router in the App Suite app.

The App Suite team has already run into this issue and their solution was to keep the server socket used by the app open after accepting the client connection until the client connection is also lost.

The work-around that we tried in SDL and gave to the partner to test is similar.  We commented out some lines in MultiplexBluetoothTransport.java:
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java#L239-L242

This leaves the server socket open until MultiplexBluetoothTransport.stop() is called.
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java#L272
This prevents the OS from assigning the channel in-use by SDL to another server socket.

**Comment by madhuy** [comment]
@joeygrover  Please let us if it has any side effects or concerns if we do changes mentioned by @jthrun in our companion app Router?

**Comment by joeygrover** [comment]
I will need some time to confirm this bug as well as attempt to troubleshoot it. I can't recommend the change until I have understood what is happening. I will be trying to acquire one of the Samsung phones mentioned to test with.

**Comment by jthrun** [comment]
We can't say for certain that it is only Samsung devices even though the partner reported the issue only listing Samsung devices.  We don't know if they have tested with any other manufacturers' devices and we have been unable to repro the issue in general.

**Comment by jthrun** [comment]
Our partner has tested this with some non-Samsung devices:

Huawei P7: 5.1.1
Sony Xperia Z1: 5.1.1
Xiaomi 5s: 6.0.1 MXB48T

They all seem to fail.  We can send you some of their logs if that might help.

**Comment by joeygrover** [comment]
Yes, please attach them here. It's seemingly a more of widespread issue so we might have to include the logic provided as a fix until (or if) a more ideal solution can be found.

**Comment by jthrun** [comment]
I don't know if they will be much help.  It looks like the partner only sent SDL Core logs.

[338logs.zip](https://github.com/smartdevicelink/sdl_android/files/539942/338logs.zip)

**Comment by jthrun** [comment]
From Joey, 

> I haven’t been able to find anything else to really deal with it at a high level. Could probably do reflection and find how to deal with it, but it doesn’t seem to have any negative impacts so I’ll probably add a PR for it in the coming week.

**Comment by theresalech** [comment]
Closed by https://github.com/smartdevicelink/sdl_android/pull/348
