### ISSUE TITLE
How to handle USB support?

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#34]
It looks like the current manifest has minSdkVersion set to 12 ([Android 3.1](http://developer.android.com/about/versions/android-3.1.html)), due to the USB support.

``` xml
<uses-sdk android:minSdkVersion="12"/>
```

If an app doesn't need USB support, the minSdkVersion can probably go back to 8 ([Android 2.2](http://developer.android.com/about/versions/android-2.2.html)), but we need to figure out how to make that work.  Maybe a different branch for USB support so master can support as many Android phones as possible over bluetooth?  Another possibility is adding gradle support to enable/disable USB within the gradle config files, but that option, of course, requires integrating gradle into the project, which is probably a different discussion.

Here's the Android documentation for [USB Accessory](http://developer.android.com/guide/topics/connectivity/usb/accessory.html), which says USB support is back-ported to sdk 10 ([Android 2.3.4](http://developer.android.com/about/versions/android-2.3.4.html)) using add-on libraries.

Any other ideas for how to handle USB support while still supporting as many phones as possible over bluetooth?

**Comment by joeygrover** [comment]
It's multiplexed now. #768
