### ISSUE TITLE
Router validator takes 5 minutes to timeout the HTTP request for createTrustedListRequest()

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#371]
When SDLRouter first sends broadcast of connection, RouterServiceValidator.createTrustedListRequest() is called.  This is sending and HTTP POST request which times out.  It seems like there is no Router-Proxy communication while this request is pending.  So HU shows error message about missing apps or just shows spinner/blank screen.  The timeout happens due to this line:

https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/RouterServiceValidator.java#L420

This just started happening with the latest release of Android SDL Library.  Did the whitelist URL change recently?  Why is this request timing out?  Also why does the timeout take so long, shouldn't it be shorter?

**Comment by joeygrover** [comment]
See PR #372 for updates.

**Comment by jthrun** [comment]
I've tried the bugfix branch with our companion app and test apps and it is working.
