### ISSUE TITLE
Possible missing error state in AcceptThread.run() of MultiplexBluetoothTransport.

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#373]
A certain stress/edge test case where BT on the HS is disabled and enabled rapidly several times in a row could result in an IOException in the code found here:

https://github.com/smartdevicelink/sdl_android/blob/bugfix/issue_371/sdl_android_lib/src/com/smartdevicelink/transport/MultiplexBluetoothTransport.java#L435-L445

The catch block doesn't set the state to ERROR but the else block above it does.  This could result in AcceptThread.run() exiting but leaving the transport in a bad state.

**Comment by joeygrover** [comment]
Fixed with PR #396
