### ISSUE TITLE
onProxyClosed() when being cycled with Multiplexing

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#431]
Before multiplexing was introduced, when the proxy was cycled, the app's SdlService's `onProxyClosed()` method would be called and it was common practice for the SdlProxy object to stop itself. 
```
public void onProxyClosed(String info, Exception e, SdlDisconnectedReason reason) {
		stopSelf();
}
```
Then, the library would start the SdlProxy object back up from scratch.

With multiplexing enabled, if the proxy is closed and the service is stopped, it is never started again. The RouterService remains connected to core, and when the proxy is to be cycled the RouterService handles sending a new RegisterAppInterface request. 

The only cases where you would want to notify the app's SdlService to stop itself are those where the RouterService can restart the service. Otherwise in a situation where you want to cycle the proxy and keep the connection intact, the SdlService will lose

**Comment by joeygrover** [comment]
Fixed with #432
