### ISSUE TITLE
Android SDL Router validation rejects all routers when it gets bad data from validation server

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#459]
Recently (today), the validation server is returning this in response to the list request:

`{"response":{}}`

This results in the router validation logic rejecting all routers.  It looks like the code that processes the list returned from the server does no validation on the list data.  It seems like cases where the server list is empty or contains no data should be treated the same as cases where the server does not respond or returns some error response code.

See 

[RouterServiceValidator.java#L418](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/RouterServiceValidator.java#L418)

**Comment by nickschwab** [comment]
Hey @jthrun, can you please provide the package names you're sending to/expecting back from the router validation service? Or are you seeing this behavior in result of a unit test?

**Comment by jthrun** [comment]
Its any of the ones that are in the "default" list hard-coded in that same file:

[RouterServiceValidator.java#L45](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/transport/RouterServiceValidator.java#L45)

**Comment by askirk** [comment]
Which branch/version of the lib were you using?

**Comment by jthrun** [comment]
Master, the 4.2.3 release commit.

**Comment by joeygrover** [comment]
I don't believe an empty set is an incorrect value. For example, if we determine one of the hardcoded apps is actually untrusted and should never have been trusted, the record might be removed from wopr.jr so it wouldn't be returned, and thus, the library would receive an empty set. 

Now, if wopr.jr is returning invalid responses, ie one of the trusted apps are installed, correct package is sent to wopr.jr, and it returns an empty set, we should address that issue. Can you validate that the request you are sending includes the packages installed?

**Comment by jthrun** [comment]
Apparently it does not.  I see the issue on my side.  The apps did not have broadcast receiver exported.  Therefore, my bad.  Did not know that was used to determine an app was an SDL app.

**Comment by joeygrover** [comment]
Ok, that makes sense. I'm going to close this issue and I've opened an issue on the documentation to make sure there is a very clear note. https://github.com/smartdevicelink/sdl_android_guides/issues/20
