### ISSUE TITLE
Is there a way to tell which buttons are available in a media application and disable them?

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_android#46]
Let's say I have a media application that allows the user to go back to the beginning of a media item and play/pause it but not go to the next media item.

Is there a way for me to disable the skip/fast forward button on the HMI so that the user is not confused, or maybe change the image to something else such as play similar?

**Comment by mikeburke106** [comment]
I think the approach for this scenario is for the HMI to only show buttons which have been subscribed to by the application.  Since this approach is specific to the HMI, not to Android libs, I'm going to close out this issue.
