### ISSUE TITLE
Code cleanup, SdlRouterService.java

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_android#460]
1. Duplicate constants for intent action:
The string "sdl.router.startservice" is defined in 2 places: TransportConstants and SdlServiceRouter and is being used interchangeably.  It's better to consolidate and define in one class.

```
public static final String START_ROUTER_SERVICE_ACTION					="sdl.router.startservice";
```
[TransportConstants](https://github.com/smartdevicelink/sdl_android/blob/303bee02221f9e8360a5a4c449c6dc501518166d/sdl_android_lib/src/com/smartdevicelink/transport/TransportConstants.java#L12)

```
public static final String START_SERVICE_ACTION							= "sdl.router.startservice";
```
[SdlServiceRouter](https://github.com/smartdevicelink/sdl_android/blob/303bee02221f9e8360a5a4c449c6dc501518166d/sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java#L98)

2. Potential NPE: int count = ... should be moved inside if (packet != null) clause
```
				int count = bundle.getInt(TransportConstants.BYTES_TO_SEND_EXTRA_COUNT, packet.length);  //In case there isn't anything just send the whole packet.
				if(packet!=null){
					mSerialService.write(packet,offset,count);
					return true;
				}
				return false;
			}
```
[Reference](https://github.com/smartdevicelink/sdl_android/blob/303bee02221f9e8360a5a4c449c6dc501518166d/sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java#L1252-L1257)

3. Potential NPE: It appears that we add the bundle to the message object; but nevertheless, should handle bundle being null here
```
if(receivedBundle!=null){
	        			receivedBundle.setClassLoader(loader);//We do this because loading a custom parceable object isn't possible without it
	            	}else{
	            		Log.e(TAG, "Bundle was null while sending packet to router service from alt transport");
	            	}
            		if(receivedBundle.containsKey(TransportConstants.FORMED_PACKET_EXTRA_NAME)){
            			SdlPacket packet = receivedBundle.getParcelable(TransportConstants.FORMED_PACKET_EXTRA_NAME);
    					if(packet!=null){
    						service.onPacketRead(packet);
    					}else{
    						Log.w(TAG, "Received null packet from alt transport service");
    					}
            		}else{
            			Log.w(TAG, "Flase positive packet reception");
            		}
```
[Reference](https://github.com/smartdevicelink/sdl_android/blob/303bee02221f9e8360a5a4c449c6dc501518166d/sdl_android_lib/src/com/smartdevicelink/transport/SdlRouterService.java#L603-L617)

**Comment by joeygrover** [comment]
Thanks for taking a look at the code! I will be closing this issue as it contains more than a single issue. Please create separate issues for each one of these findings so that PRs can be opened against each of them individually.

**Comment by Tnnnguyen** [comment]
@joeygrover thanks, will break it down to separated issues.
