### ISSUE TITLE
[SDL 0051] Enhance Video Streaming API's for Android

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_android#469]
Proposal: [Enhance Video Streaming API's for Android](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0051-enhance_video_streaming_apis_for_android.md)

> This proposal is to add APIs to the current SDL Android library that provide an enhanced ability for developers to stream video through SDL's video streaming capabilities. The new APIs will leverage native OS classes that developers will understand.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/152

Steering Committee Decision:

> The Steering Committee voted to accept this proposal, after discussing that a note clarifying API level should be included when this feature is released. As the previous method for video streaming will still exist (not deprecated), it will be up to the developer if they want to support older versions of Android or use the enhanced API. The Steering Committee will also need to clarify which version will be used for certification, or if all versions will need to be tested for certification purposes.

**Comment by brettywhite** [comment]
closing as this is merged into develop
