### ISSUE TITLE
SdlBroadcastReceiver handling an empty ComponentName in its received intent

### ISSUE THREAD

**Issue by askirk** [smartdevicelink/sdl_android#472]
The SdlBroadcastReceiver currently enables SDL Services if the running router service's ComponentName is provided in the broadcasted intent. If the ComponentName in the intent is null, the SdlBroadcastReceiver should query to get the currently running router service's ComponentName here: https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L105
and then perform the same operations as in to eventually enable app's SDL Services
https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L89-L102

**Comment by joeygrover** [comment]
This behavior should never be observed with a properly functioning `SdlRouterService`. Will not fix.
