### ISSUE TITLE
Softbutton not displayed with show request

### ISSUE THREAD

**Issue by KennyLv** [smartdevicelink/sdl_android#505]
List<SoftButton> softButtons = new ArrayList<>();
                                SoftButton btn_1 = new SoftButton();
                                btn_1.setType(SoftButtonType.SBT_TEXT);
                                btn_1.setText("Button1");
                                softButtons.add(btn_1);
                                SoftButton btn_2 = new SoftButton();
                                btn_2.setType(SoftButtonType.SBT_TEXT);
                                btn_2.setText("Button1");
                                softButtons.add(btn_2);
                                SoftButton btn_3 = new SoftButton();
                                btn_3.setType(SoftButtonType.SBT_TEXT);
                                btn_3.setText("Button1");
                                softButtons.add(btn_3);

                                Show showRequest = new Show();
                                showRequest.setSoftButtons(softButtons);
                                showRequest.setCorrelationID(CorrelationIdGenerator.generateId());
                                showRequest.setOnRPCResponseListener(new OnRPCResponseListener() {
                                    @Override
                                    public void onResponse(int correlationId, RPCResponse response) {
                                        if (((ShowResponse) response).getSuccess()) {
                                            Log.i("SdlService", "SoftButton Successfully showed.");
                                        } else {
                                            Log.i("SdlService", "SoftButton Show request was rejected.");
                                        }
                                    }
                                });
                                proxy.sendRPCRequest(showRequest);

**Comment by KennyLv** [comment]
Using template TEXTBUTTONS_ONLY / TEXTBUTTONS_WITH_GRAPHIC

**Comment by brettywhite** [comment]
Hi, For each button you need to include an unique ID parameter: `btn_1.setSoftButtonID(0);` for example. I did notice this is missing in the example documentation and will create an issue with that to update it.
