### ISSUE TITLE
Purpose/neccessity of SiphonServer?

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_android#51]
Is [this class](https://github.com/smartdevicelink/sdl_android/blob/5a9cc2c6067a6063a1e1441a0c0194ca4215cf2a/sdl_android_lib/src/com/smartdevicelink/transport/SiphonServer.java) still needed? It seems like it's mostly just for debugging and I think there are much better ways to handle debugging rather than this. (Lot less overhead).

**Comment by mrapitis** [comment]
Hi Joey,
We do use the siphon server and siphon tool to troubleshoot and debug issues (usually helpful when investigating a problem at the protocol and transport levels).  We are working on a branch that will be pushed soon that includes some siphon server thread and port clean up (as threads and ports were not being closed properly).  Ideas to reduce the overhead used by siphon or other transport / protocol debugging ideas are welcome
Thanks

**Comment by joeygrover** [comment]
I would imagine a custom logger class that extends on the Android Log class would be much simpler. Just enable a trace method that only outputs when set to on. This is the process I have used many times.  Having the extra sockets and threads seems like reinventing the wheel. 

If the Siphon Server method of debugging is still needed I would suggest moving it into a utility/extension lib, not the main library as most developers won't need it and it causes bloat.

**Comment by Heath-FoMoCo** [comment]
I think this is still needed until something better is implemented.  We still use frequently to debug with partner apps.

**Comment by tpulatha** [comment]
The big advantage of Siphon is that we can log the calls live through wifi. This would be a requirement for all successors in my opinion

**Comment by joeygrover** [comment]
I agree it's still needed until something else is implemented. Since wifi logging can be achieved through Logcat as well, I would like to see logging move more towards the native Android solution rather than maintaing a custom one.

**Comment by Heath-FoMoCo** [comment]
We also have to be mindful of an iOS solution as well.

**Comment by mikeburke106** [comment]
I don't think we should let the features of one platform dictate our decision-making process on the other platforms if we can avoid it.  I'm sure there are dozens of open-source projects for iOS that do the same thing as Logcat.  Also, agree with Joey that this is better suited for an add-on debug library or something and doesn't really belong in the lightweight mobile libs themselves.

Not going to change overnight, obviously, but if this is a feature that is necessary, we should have a plan to split out debug code into a separate library so we can keep the mobile libraries as light as possible, which we've been told is a goal of the project.

**Comment by Heath-FoMoCo** [comment]
Don’t get me wrong.  I am not saying that we have to have the same solution for both or all.  I am just saying when we come up with a compensating solution for Android we have to do the same for iOS.

**Comment by idamaster** [comment]
The nice thing about siphon is that it's a boolean that can be switched on with little to no effort that gets us additional logging and requires no further effort from the mobile dev. 

We need to find a balance, and I think the team can likely find a better technical solution, but I'd start with highlighting the goals we're looking to achieve: Simplify effort for developers, think of those who need to get/read debug results, keep libraries lightweight, etc.

**Comment by joeygrover** [comment]
I've already wrote a basic one for the SDL Core Android port I made. I just made a temp commit in the multiplexing branch of this project to share it. You can view it <a href="https://github.com/smartdevicelink/sdl_android/blob/multiplexing/sdl_android_lib/src/com/smartdevicelink/util/SdlLog.java">here.</a>

The trace methods obviously need to be extended to show direction of packets and such that existed in SiphonServer.

**Comment by mikeburke106** [comment]
Also, with more advanced builds (read: gradle), we could omit debug code like this in production builds to keep the libs lightweight.

**Comment by mikeburke106** [comment]
Could someone explain how to use the SiphonServer to get the log messages?  I see where the enable the SiphonServer in the SyncProxyTester, but how do I actually look at the logs?

**Comment by PKramchaninov** [comment]
As far as I know there is a special Windows desktop tool called ApplinkDebugTool. It get logs from the SiphonServer over Wi-Fi. I guess Ford team can provide more details on this.

**Comment by mikeburke106** [comment]
Thanks for the info, Pavel.

So, it sounds like SiphonServer is a Ford-specific feature that requires proprietary Ford software to function?  Unless there are plans to open-source the windows application software and port to other environments, this sounds out of the scope of the open-source SDL development.

I would tend to agree with Joey that this feature should be removed from the project and we should investigate alternative logging solutions that are cross-platform and available for anyone to use without Ford proprietary software.  Anyone agree or disagree?

**Comment by Heath-FoMoCo** [comment]
Agree.

**Comment by joeljfischer** [comment]
Yeah I agree. We should discuss the alternatives, but I think it should probably be removed, since it is dependent upon closed software that our users don't have access to.

The alternative I would propose, at least on iOS (since android has native remote logging) is a webserver  that serves a webpage which displays the remote logs. Similar to: https://github.com/CocoaLumberjack/CocoaLumberjack/tree/master/Demos/WebServerIPhone
