### ISSUE TITLE
Wrong argument in DisplayCapabilities method

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_android#52]
com.smartdevicelink.proxy.rpc.DisplayCapabilities has this method:
160: `setImageFields( List<TextField> imageFields )`
The parameter should be of type `List<ImageField>`

**Comment by mikeburke106** [comment]
Good find, Chris.  We actually already fixed this issue in commit 8196a019efd7ef0b0f01ca2dffe7c26a97ab9264, but it looks like it was incorrectly merged back in in commit 43d5fd5d8ada2b8e8ccad360e315e6dc9523409f.

This is why the unit test stuff you're working on is so important.  Little mistakes like this can be found more easily.  Keep up the good work.
