### ISSUE TITLE
SdlProxyBase doesn't update DisplayCapabilities on SetDisplayLayoutResponse

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_android#53]
Mike: SdlProxyBase keeps a global variable containing the display capabilities for the head-unit.  This global variable is only set on register app interface - it isn't updated when the layout changes.  When the layout changes, size of images, number of text fields, etc may change, so the global variable should be updated to reflect these changes.

**Comment by mrapitis** [comment]
Thats a good catch, we actually need to update the proxy objects displayCapabilities, buttonCapabilities and presetBankCapabilities when a successful setDisplayLayout change occurs.
