### ISSUE TITLE
android:debuggable="true" In manifest leads to app Rejection

### ISSUE THREAD

**Issue by martin-price87** [smartdevicelink/sdl_android#540]
android:debuggable="true" should be removed from the manifest.

As this is a library to be used within other projects android:debuggable="true" should not be set in the manifest. When a release apk is assembled a project using this library the android:debuggable="true" will be merged into said projects manifest resulting in a debuggable release apk which will promptly be rejected by Google.

I can see this was added due to this ticket https://github.com/smartdevicelink/sdl_android/issues/40. If you want to disable logs you can do so using custom BuildConfig flags defined within the library gradle file and referencing them in the code. i.e buildConfigField "boolean", "LOG", "false" and then if (!BuildConfig.LOG) // disable logging

**Comment by joeygrover** [comment]
Fixed with hotfix release https://github.com/smartdevicelink/sdl_android/releases/tag/4.3.1
