### ISSUE TITLE
Potential Bugs from FindBugs Reports

### ISSUE THREAD

**Issue by BrandonHe** [smartdevicelink/sdl_android#544]
**Introduction**
We have one partner who is integrating android proxy to their mobile navigation app.
They used [FindBugs 3.0.1](http://findbugs.sourceforge.net/) to analyse sdl_android v4.3.0, a lot of potential issues are found, including many high priority warnings, they had selectively fixed some concern and troubling issues and recommend to fix all the scary and scariest issues.
For potential error levels see [wiki](https://en.wikipedia.org/wiki/FindBugs)

**Reports summary:**
24622 lines of code analyzed, in 470 classes, in 23 packages.

|Metric |	Total | 	Density* |
|---------|-----------|------------|
High Priority Warnings |	23 |	0.93 |
Medium Priority Warnings |	137 | 5.56 |
Total Warnings |	160	| 6.50 |

| Warning Type |	Number |
|--------------------------|--------|
| Bad practice Warnings	| 20     |
| Correctness Warnings	| 12     | 
| Internationalization Warnings  | 	6 |
| Malicious code vulnerability Warnings |	21 |
| Multithreaded correctness Warnings	| 28 |
| Performance Warnings	| 28 |
| Dodgy code Warnings	| 45 | 
| Total	| 160 |

**Details Reports**
[FindBugs.zip](https://github.com/smartdevicelink/sdl_android/files/1084466/FindBugs.zip)

**Suggestion**
Recommend to fix all the scary and scariest issues that FindBug complains

**Comment by askirk** [comment]
After looking at the report, I did not see any bugs in that list that warrant immediate concern, even the ones marked as "High Priority". Fixing these bugs are a low priority for now.

**Comment by brettywhite** [comment]
Also, while FindBugs was made for Java, it may not know best practices for the Android implementation of Java or the idiosyncrasies of the Android platform, raising false warnings

**Comment by BrandonHe** [comment]
@askirk @brettywhite Thanks for your reply. 
Here is just information that we found for you, it may include your concerns or potential issues need to be fixed.
