### ISSUE TITLE
Improve Android Multiplexing app's connection time

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_android#550]
Apps using multiplex currently suffer a long connection time during head unit reset.
The average time it takes to reconnect is typically 22 - 23 seconds while it's a few seconds for non-multiplexing apps.
This prolonged connection time (for multiplexing) misleads apps developers to think there is an issue with either their apps or the library. Ultimately, it can potentially mislead the end users to think that these apps cannot be connected just because other apps (non-multiplexing) already show and the multiplexing apps take more than 10 seconds extra.

This issue was brought up by the Alexa Android team.
We perform our own tests base on their feedback. Here is a test module that tests one multiplexing app's connection time on head unit reset:

### 1. Test connection time elapse difference when trusted list is downloaded and when it's not.
a. Delete Hello Sdl app from device
b. Install Hello Sdl app
c. Power up head unit, tap to start Hello Sdl app, connect mobile apps on head unit
d. Wait for Hello Sdl app to connect

Run 2nd to run 6th:
a. With app still connected, turn off then turn on head unit
b. Wait for Hello Sdl app to connect

**Observations**:
- The trusted list is downloaded on the first run and it is not downloaded thereafter as expected
- _The bottle neck of about 20 seconds is found  before the trusted list is downloaded._ 
- Subsequent runs still take over 20 seconds to connect without trusted list being downloaded.
- The first run takes 23 seconds while the subsequent runs take 21 - 22 seconds. This maps very well to the fact that the first run downloads the trusted list while the subsequent runs do not.
- The time it takes to download the trusted list is normally less than 1 (one) seconds as confirmed in test 2. of this module.

**Conclusion**:
- If we can improve the connection time if we can shorten the bottleneck described in above observations, regardless of the trusted list being downloaded or not. 

#### Test results:
| Run  |  Total Connection Time (seconds) | Trusted List Downloaded |
| :---: | :---: | :---: |
| 1st   | 23 | Yes |
| 2nd | 22 | No |
| 3rd | 22 | No |
| 4th | 21 | No |
| 5th | 22 | No |
| 6th | 22 | No |

### 2. Test trusted list download time.
a. With head unit on, delete Hello Sdl app from device
b. Install Hello Sdl app, connect mobile apps, wait for Hello Sdl app to connect
c. Repeat step a. and b.

**Observations**:
- The time it takes to download the trusted list is between the call `HttpRequestTask, doInBackground` and the call `SdlBroadcastReceiver, onReceive, onListObtained`
- After 6 runs, they are: 0.8, 1.0, 0.8, 0.7, 0.8, and 0,7 seconds.

**Conclusion**:
- The time to download the trusted list is normally less than a second and is not the main cause of the prolonged connection time which usually take more than 20 seconds.

#### Test Results:

| Run  |  Total Download Time (seconds) | 
| :---: | :---: | 
| 1st | ~ 0.8 |
| 2nd | ~ 1.0 | 
| 3rd | ~ 0.8 |
| 4th | ~ 0.7 |
| 5th | ~ 0.8 |
| 6th | ~ 0.7 |

## What we learn from the above tests:
- The trusted list downloading time is insignificant as compared to the total connection time.
- The bottleneck happens when `SdlBroadcastReceiver.java` is waiting to receive a broadcast sent from `SdlRouterService.java`, `onTransportConnected` method.
- As this broadcast is controlled by the OS, at times, it takes too long to be sent out (typically 20 seconds, reason is unknown at this time).
- We can improve the queue time of the broadcast by giving it foreground priority with the flag `Intent.FLAG_RECEIVER_FOREGROUND`
- As tested with fix (see Module 8 below), the connection time is improved significantly and the multiplexing app gets detected at the same time as non-multiplex apps on a head unit reset.

---
## Module 8: Test Hello Sdl app connection time with broadcast priority increased to foreground process

In `SdlRouterService.java`, method `public void onTransportConnected(final TransportType type)`: attach an extra flag to the intent `startService.addFlags(Intent.FLAG_RECEIVER_FOREGROUND)`

### 1. Test Hello Sdl app's connection time with other BT apps (iHeartAuto and Accuweather) when resetting head unit; Hello Sdl is using Multiplex (mbt_offDebug build)
a. Install Hello Sdl, iHeartAuto and Accuweather apsp and connect mobile apps on head unit; observe that all 3 appear on head unit
b. Turn off, turn on head unit
c. Tap Apps and wait for apps to show

**Observations**:
- All 3 apps are detected almost at the same time on the head unit (Accuweather sometimes is not)
- After 6 runs, the total connection times for Hello Sdl app for each run are (in seconds): 3, 4, 5, 7, 5, 4.
- These times are much better than the ones recorded in Module 7, Test 1 which are at 22 - 23 seconds

**Conclusion**:
- Multiplexing app's connection time is improved significantly when we set the priority of the broadcast to start router service to foreground process priority (high).

#### Test Results (with foreground priority flag):
| Run | Total Connection Time (seconds) |
| :---: | :---: |
| 1st | 3 |
| 2nd | 4 |
| 3rd | 5 |
| 4th | 7 |
| 5th | 5 |
| 6th | 4 |

### 2. Test Hello Sdl app's connection time when downloading trusted list
a. With head unit on and Hello Sdl app connected/detected, delete Hello Sdl app from device
b. Install Hello Sdl app, connect mobile apps, wait for Hello Sdl app to connect
c. Repeat step a. and b.

**Observations**:
- The time it takes to connect including trusted list download is not significantly longer than when the list is not downloaded
- After 5 runs the total time to connect for each run are (in seconds): 7, 5, 5, 8, 6.

**Conclusions**:
- Downloading the trusted list does not significantly increase the connection time for Multiplexing app with foreground priority flag set for broadcast.

#### Test Results (with foreground priority flag):
| Run | Total Connection Time (seconds) | Trusted List Download Time (seconds)|
| :---: | :---: | :---: |
| 1st | 7 | ~ 0.6 |
| 2nd | 5 | ~ 0.9 |
| 3rd | 5 | ~ 0.7 |
| 4th | 8 | ~ 0.8 |
| 5th | 6 | ~ 0.4 |

**Comment by joeygrover** [comment]
Hi @Tnnnguyen ,

Thank you for the in-depth tests around this! It is very interesting to see the difference.

I'm currently working on an evolution proposal for dealing with Android O changes that actually does include this flag for other reasons. I was waiting until I had finished all my investigation to create a large proposal but I believe based on this new information I should submit them in two phases. I will submit a phase 1 proposal that includes this flag and other minor changes in the router service. The second phase will come later when I have more information and a complete plan on how to handle a different restriction Android O will introduce.

**Comment by joeygrover** [comment]
Solved with #556
