### ISSUE TITLE
onProxyClosed called right after language change

### ISSUE THREAD

**Issue by Wexlajs** [smartdevicelink/sdl_android#558]
Changing the language on the headunit the onProxyClosed event will be called with LANGUAGE_CHANGE. The proxy will be restarted but right after that, onProxyClosed will be called with GENERIC_ERROR. Observed on the Hello SDL example.

**Comment by brettywhite** [comment]
@Wexlajs Is this on a TDK? Emulator? What protocol were you using? Version of the example app? android version? phone model or emulator? Please provide more context when raising an issue.

**Comment by Wexlajs** [comment]
Sorry, its the latest hello sdl example app version 4.3.0, it was observed on a TDK using an USB connection. It was tested on Samsung Galaxy S5 and Samsung Galaxy Note 4 (both 6.0.1 android version)

**Comment by brettywhite** [comment]
Hi @Wexlajs, 

Sorry about responding to this so far after. I just took a look at it today using an original pixel running 8, Ford TDK and the current develop branch of sdl_android and It appears to not send the second `onProxyClosed`, just the first one with the reason `LANGUAGE_CHANGE`. I'm not sure if you were still working on this or if it was resolved for you. 

Please let me know. Thanks

**Comment by brettywhite** [comment]
Closing due to inability to reproduce
