### ISSUE TITLE
Typedef exceptions can occur when utilizing vehicle data getter methods that return Doubles

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#57]
Currently this is an issue for getVehicleData and SubscribeVehicleData rpc's.  
When receiving float based values from sdl core that do not include a decimal (e.g. 80) internal objects are stored as integers causing casting exceptions to occur when values are returned via rpc getter methods (e.g. getSpeed).

**Comment by mikeburke106** [comment]
I don't think this is an issue with the Android libraries, this is an issue with versions of SDL core not meeting the specification, but yeah, the Android libs need to support this incorrect behavior from SDL core.  An issue should be filed for SDL core as well, unless this has been fixed core-side already.

I think this needs to be maintained as part of a list of "hacks" required to support backwards compatibility issues.
