### ISSUE TITLE
USB connection issues with Samsung devices

### ISSUE THREAD

**Issue by meeej** [smartdevicelink/sdl_android#585]
We have having problems detecting Samsung devices using USB connection. We defined a USB intent filter in our AndroidManifest.xml:
```
<activity
        android:name="com.smartdevicelink.transport.USBAccessoryAttachmentActivity"
        android:launchMode="singleTop">
        <intent-filter>
            <action android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED"/>
        </intent-filter>

        <meta-data
            android:name="android.hardware.usb.action.USB_ACCESSORY_ATTACHED"
            android:resource="@xml/accessory_filter"/>
</activity>
```
then we launch USBAccessoryAttachmentActivity which executes the following code:
```
if (UsbManager.ACTION_USB_ACCESSORY_ATTACHED.equals(action)) {
            Intent usbAccessoryAttachedIntent = new Intent(USBTransport.ACTION_USB_ACCESSORY_ATTACHED);
            usbAccessoryAttachedIntent.putExtra(UsbManager.EXTRA_ACCESSORY, (Parcelable) intent.getParcelableExtra(UsbManager.EXTRA_ACCESSORY));
            usbAccessoryAttachedIntent.putExtra(UsbManager.EXTRA_PERMISSION_GRANTED, (Parcelable) intent.getParcelableExtra(UsbManager.EXTRA_PERMISSION_GRANTED));
            sendBroadcast(usbAccessoryAttachedIntent);
        }
```
this will send a broadcast and will be received by out SdlReceiver which extends SDLBroadcastReceiver. In SdlReceiver, we override the onReceive method:
```
@Override
    public void onReceive(final Context context, final Intent intent) {
        final String action = intent.getAction();
        if (ACTION_ATTACHED.equals(action)) {
            final UsbAccessory usbAccessory = intent.getParcelableExtra(UsbManager.EXTRA_ACCESSORY);
            if (USBTransport.isAccessorySupported(usbAccessory)) {
                final Intent intent1 = new Intent(context, SDLControllerService.class);
                intent1.setAction(ControllerService.ACTION_CONNECT);
                intent1.putExtra(UsbManager.EXTRA_ACCESSORY, usbAccessory);
                intent1.putExtra(UsbManager.EXTRA_PERMISSION_GRANTED, (Parcelable) intent.getParcelableExtra(UsbManager.EXTRA_PERMISSION_GRANTED));
                context.startService(intent1);
            }
        }
    }
```

Now the problem with Samsung devices is that the first time we connect the phone with USB, the onReceive is executed but subsequent USB connections after detaching USB will not execute onReceive unless we go to settings and force stop the app or after waiting at least ten to thirty minutes.

**Comment by brettywhite** [comment]
Hi @meeej,
I just tried this out on my S7 and had no issues working with USB on my TDK. I tried pulling the cord, killing the app from both the phone and the SDL app itself and it always reconnected as expected.

A little about my setup - I am testing with the [hello sdl android](https://github.com/smartdevicelink/hello_sdl_android) app and using the develop branch of sdl_android.

Are you using a TDK? If so whats the version on it? Which branch or version of SDL Android are you testing with? What Samsung devices?

**Comment by brettywhite** [comment]
It also seems like you are missing items in your manifest and starting the service incorrectly (based on the code given) Please follow this [guide](https://smartdevicelink.com/en/guides/android/getting-started/using-aoa-protocol/)

**Comment by meeej** [comment]
Hi @brettywhite, thank you for the reply. When you said "pulling the cord, killing the app from both the phone and the SDL app itself" did you have to manually kill the app in the "App overview" view to the left of the home button or was pulling the cord the only thing you did? I am using a Samsung Galaxy S7 edge and it will reconnect if I unplug then manually killing the app but it would not reconnect if I only unplug the USB.

Device: Samsung Galaxy S7 edge
SDL Android version: 4.3
Testing on Web HMI

**Comment by brettywhite** [comment]
Yes, i pulled the cord some times and other times i killed the app from the phone itself without pulling the cord. I suggest reading through the guide I linked above and making sure you are using the built in way of starting the service, and have the proper manifest items in place.

**Comment by meeej** [comment]
I have a few questions about the code in the guide. What does forceOnConnected() do? The documentation isn't very clear on this one. Also would it matter if I used MultiplexTransportConfig instead of USBTransportConfig when creating my sdlProxy?

**Comment by brettywhite** [comment]
For questions like that I am going to refer you to our slack channel: http://slack.smartdevicelink.com/ specifically the android-help channel.

**Comment by meeej** [comment]
@brettywhite thanks! You've been a great help.

**Comment by Tnnnguyen** [comment]
@meeej , @brettywhite 

> I am using a Samsung Galaxy S7 edge and it will reconnect if I unplug then manually killing the app but it would not reconnect if I only unplug the USB.
>
I came across this behavior a few times when using USB (Samsung Note 5). My speculation is that the broadcast `ACTION_USB_ACCESSORY_DETACHED` is not handled correctly. Only force-killing the app will reconnect as it kills the app's process. Swipe to close will not work.

**Comment by Wexlajs** [comment]
you can achieve this behaviour with the latest hello sdl app if you start the app you have it in foreground plug it to the TDK (connection will be established) and then when you just disconnect the usb and connect again (without doing anything with the app) -> no connection will start, until you kill the app and connect again. I was able to reproduce this on samsung A3, samsung galaxy S8, samsung note, google nexus 4

**Comment by joeygrover** [comment]
A new USB transport has been implemented and stability improved in the next release. See #933
