### ISSUE TITLE
Broadcast logging can cause an exception if the apps service becomes unavailable

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#59]
If the apps service becomes unexpectedly unavailable.  In the code below, if the service becomes unavailable the getApplicationContext call will fail causing an exception.

```java
private void sendBroadcastIntent(Intent sendIntent)
	{
		Service myService = null;		
		if (_proxyListener != null && _proxyListener instanceof Service)
		{
			myService = (Service) _proxyListener;				
		}
		else if (_appService != null)
		{
			myService = _appService;
		}
		else
		{
			return;
		}
		Context myContext = myService.getApplicationContext();
		if (myContext != null) myContext.sendBroadcast(sendIntent);		
	}
```

**Comment by mikeburke106** [comment]
I think this is going to be a higher-level "logging" discussion, possibly related to #51.  Sending logs via broadcast intent doesn't really make much sense to me, especially from a background service.
