### ISSUE TITLE
Bloater code smell

### ISSUE THREAD

**Issue by poborin** [smartdevicelink/sdl_android#607]
Hi there,

there is a SdlProxyALM class in the SDK. 1500 lines of almost 2000 lines. There are 38 contractors and a good half of them is deprecated. Meanwhile there is a SDLProxyBuilder class that basically does the same thing but in a nicer manner.

I would like to suggest to deprecate the entire class and use a builder only as it's almost impossible to keep track on what happens with contractors in SdlProxyALM. Or create a base constructor that uses required parameters meanwhile all other could be set by builder.

**Comment by joeygrover** [comment]
Thanks for your interest in the project. I am closing this issue as it is not a specific issue with the library but rather a comment about it. While I agree with the comment and need for change, it is not specifically an addressable issue. If you would like to see changes please submit an evolution proposal [here](https://github.com/smartdevicelink/sdl_evolution) and the change can get processed through.
