### ISSUE TITLE
Out-of-Memory while SdlRouter processes incoming data from BT socket

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#616]
We have two instances where testing has found an SDL app to be apparently unresponsive to HU messages.  Looking at the logcat logs reveals that the Router had run out of memory while processing messages coming in over the BT socket.  The questions are:

- Is there a memory leak somewhere?
- What messages are so big that they can't be handled?

I don't think there is a leak because we'd see more problems like this more often.   In both case the log has messages like these:
```
09-18 13:55:04.200 16560 17032 I art     : Forcing collection of SoftReferences for 1GB allocation
...
09-18 13:55:04.260 16560 17032 W art     : Throwing OutOfMemoryError "Failed to allocate a 1886416766 byte allocation with 4194304 free bytes and 252MB until OOM" 
```

What message is 1GB?  That seems kind of large for an SDL RPC coming from the HU.

I'm attaching the logs from the two cases.  In one case the Router's PID is 16560 and in the other it is 19953 but searching for "OutOfMemory" will find the location in the log files.

Also, customer is of the opinion that this situation isn't handled very gracefully.  I'm not sure I agree since the Router is not crashing but throwing away the data and eventually seems to recover from the situation and begins processing messages again.

[19400.txt](https://github.com/smartdevicelink/sdl_android/files/1330822/19400.txt)
[19682.log](https://github.com/smartdevicelink/sdl_android/files/1330830/19682.log)

**Comment by joeygrover** [comment]
What branch/release is being used? This can happen when data is corrupted and the PSM tries to allocate an incorrect payload buffer.

**Comment by jthrun** [comment]
Latest release from master (4.3.1) with the following additions:

- cherry-picked change for #554 
- local change to fix #586 
- local change to catch ArrayIndexOutOfBoundsException in BinaryFrameHeader
- some added logging

**Comment by brettywhite** [comment]
After speaking with the author, it seems that the issue was stemming from bad packets coming from a head unit. An in depth look at the code was taken to insure there were no memory leaks. A potential NPE was found during and references this issue above.

**Comment by joeygrover** [comment]
Closing as not reproducible.
