### ISSUE TITLE
[SDL 0101] Add Android SDL Internal Interface

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_android#619]
Proposal: [Add Android SDL Internal Interface](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0101-android_internal_interface.md)

>The internal SDL interface will help reduce the dependency on the SDLProxyBase class and allow us to move away from it in the future when we introduce a more enhanced framework.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/298

**Comment by brettywhite** [comment]
PR Merged, closing issue
