### ISSUE TITLE
createOpenGLInputSurface should check if protocol version < 5

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#638]
createOpenGLInputSurface in SdlProxyBase is currently failing for protocol versions that are less than 5.
The tryStartVideoStream method will always return null if the protocol version is less than 5, as a result the createOpenGLInputSurface will fail to be called (for any protocol version below 5).  Please see code block below:
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java#L4032-L4038

We need to add an else if statement similar to the block linked below from the startVideoStream method where we check to see if the protocol version is less than 5 before attempting to createOpenGLInputSurface. 
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java#L3956-L3958

Please see code snippet below for a sample solution:
```
        if (acceptedParams != null) {
            return sdlSession.createOpenGLInputSurface(frameRate, iFrameInterval, width,
                    height, bitrate, SessionType.NAV, sdlSession.getSessionId());
        } else if(getWiProVersion() < 5){
			sdlSession.setAcceptedVideoParams(new VideoStreamingParameters());
			return sdlSession.createOpenGLInputSurface(frameRate, iFrameInterval, width,
					height, bitrate, SessionType.NAV, sdlSession.getSessionId());
		} else {
            return null;
        }
```

**Comment by joeygrover** [comment]
Fixed with #646
