### ISSUE TITLE
Process condition in protocol version less than 5

### ISSUE THREAD

**Issue by BrandonHe** [smartdevicelink/sdl_android#643]
Here we found two issues in `develop` branch:

1. startVideoStream will execute on NACK
2. createOpenGLInputSurface never executed if protocol version < 5, this issue seems fixed in #638

`StartVideoStream()` method in SdlProxyBase currently return `sdlSession.startVideoStream()` if protocol version is less than 5, but `acceptedParams` has already returned **null**, this not make sense.

Below is the code snippet:
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java#L3956-L3958

`tryStartVideoStream` method in SdlProxyBase, in `if(navServiceStartResponse)` condition, if protocol version is less than 5, `getAcceptedVideoParams` will return **null**,  VideoParams will not send to proxy, leads the VideoStream never start.
Below is the code snippet:
https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java#L4148-L4150

**Comment by joeygrover** [comment]
Fixed with #646
