### ISSUE TITLE
getting INVALID_DATA response onCreateInteractionChoiceSetResponse

### ISSUE THREAD

**Issue by rahulk11** [smartdevicelink/sdl_android#647]
### Bug Report
Failing to create a custom menu as it is giving INVALID_DATA response. 
To create a custom menu, i followed the guide given here: https://smartdevicelink.com/en/guides/android/displaying-information/menus/

##### OS & Version Information
* Android Version: 7.1.2
* SDL Android Version: 4.3
* Testing Against: ford's sync3 emulator

##### Test Case, Sample Code, and / or Example App
https://github.com/rahulk11/hello_sdl_android

**Comment by brettywhite** [comment]
@rahulk11 I took a look at the forked code and I don't see that you are creating a `PerformInteraction` after creating the choice set. (the code below the choice set stuff on that guide page). Please read through the entire document and in the future paste the exact code or a gist of the code that is failing. I am closing as this is not an issue with the library. For help, take a look at our slack channel: http://slack.smartdevicelink.com

**Comment by rahulk11** [comment]
@brettywhite yes i didn't create a `PerformInteraction `because that is needed only if `CreateInteractionChoiceSet` executes successfully. BTW, i also have tried it with `PerformInteraction` with no success

**Comment by rahulk11** [comment]
@brettywhite i would request you to please open this issue again

**Comment by joeygrover** [comment]
@rahulk11 this is not an issue in the library. There is an issue with your code. You do not set the VR commands for each of the Choice objects which is a required parameter for the message. The guide is missing this information, but the details can be found in the RPC spec. 

```java
    Choice choice1 = new Choice();
    choice1.setChoiceID(uniqueChoiceID++);
    choice1.setMenuName("chapter 1");
    
    //Add this line
    choice1.setVrCommands(Arrays.asList("chapter 1" ));
```

**Comment by rahulk11** [comment]
To explain the bug: This is my method to create custom menu
```
private void sendInteractionChoiceSet() {

        CreateInteractionChoiceSet choiceSet = new CreateInteractionChoiceSet();

        Choice choice1 = new Choice();
        choice1.setChoiceID(uniqueChoiceID++);
        choice1.setMenuName("chapter 1");

        Choice choice2 = new Choice();
        choice2.setChoiceID(uniqueChoiceID++);
        choice2.setMenuName("chapter 2");

        List<Choice> choiceList = new ArrayList<>();
        choiceList.add(choice1);
        choiceList.add(choice2);

        choiceSet.setChoiceSet(choiceList);
        choiceSet.setInteractionChoiceSetID(uniqueIntChoiceSetID);
        choiceSet.setCorrelationID(CorrelationIdGenerator.generateId());
        choiceSet.setOnRPCResponseListener(new OnRPCResponseListener() {
            @Override
            public void onResponse(int correlationId, RPCResponse response) {
                if (((CreateInteractionChoiceSetResponse) response).getSuccess()) {
                    Log.i("SdlService", "The request was successful, now send the SDLPerformInteraction RPC");
                } else {
                    Log.i("SdlService", "The request was unsuccessful");
                }
            }
        });

        try {
            proxy.sendRPCRequest(choiceSet);
        } catch (SdlException e) {
            e.printStackTrace();
        }
    }
```

Now i will `PerformInteraction` only if it gives response as `SUCCESS` but it is giving `INVALID_DATA` response in `onCreateInteractionChoiceSetResponse `and it never goes to `OnRPCResponseListener` that i've set on `choiceSet` above.

```
@Override
public void onCreateInteractionChoiceSetResponse(CreateInteractionChoiceSetResponse response) {
	Log.e(TAG, "CreateInteractionChoiceSet response from SDL: "
        + response.getResultCode().name()
        + ", Success: "+ response.getSuccess()
        + ", Info: " + response.getInfo()); 
}
```

**Comment by rahulk11** [comment]
@joeygrover Ok, i'll try that and will update here if it works or not. Thanks

**Comment by rahulk11** [comment]
@joeygrover It worked. Thanks a lot.
So much of time wasted just because of that stupid guide. 

Thanks again

**Comment by joeygrover** [comment]
No problem. I have created an issue on the guides. Next time try the Slack team first and you will get answers from other people in the community before raising an issue on the library. Locking this issue from here.
