### ISSUE TITLE
App gets unexpectedly unregistered when stopped and then restarted on HS.

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_android#660]
### Bug Report
I have a case where apps are being stopped (removed from recents list) several times and then restarted (both from dead app ping and from user relaunching app on HS).  Each time this happens the Router sends an UnregisterAppInterface request to SDLCore because "binder died for app..."
At the point where something bad happens, SDLCore sends a delayed (1 minute) UnregisterAppInterface response which router passes on to app's SDLProxy.  Proxy seems to disconnect because it later gets an OnHMIStatus FULL notification but when trying to send further RPCs to SDLCore the SDLProxy throws "SDL_UNAVAILABLE" exceptions.

Here are some relevant snippets from the log.
App is removed from recents list: https://gist.github.com/jthrun/c054c7c2093bd30d11225d203edd4cd5
App reregisters with router and sends registration messages to SDLCore: https://gist.github.com/jthrun/73abb7ce10ad0222d0a8acd737c40da9
App receives unregister response, I'm guessing this is from the createForceUnregisterApp() of one minute earlier: https://gist.github.com/jthrun/7711eb386e88c37307a84a540f3204d0
App then receives `OnHMIStatus` and tries to send RPCs but can't: https://gist.github.com/jthrun/9e43f9007d28cbe7731abb8439df83e7

##### Reproduction Steps
1. Launch _CTS Media 1_ app on the HU (do not launch on the HS) 
2. Allow HS to sit idle for 3 minutes 
3. Launch _Screens_ app on the HU and then HS
4. Launch _Simple_ app on the HU and then HS
5. Press **Back** HK to close _Simple_ app on the HU
6. Swipe close _Screens_ and _Simple_ apps on the HS
7. Launch _Simple_ app on the HU and then HS
8. Launch _Screens_ app on the HU and then HS
9. Press **Back** HK to close _Simple_ app on the HU
10. Swipe close _Screens_ and _Simple_ apps on the HU
11. Repeat steps 3-10 two more times
12. Launch _Simple_ app on the HU and HS
13. Press the **Back** HK to close _Simple_ app on the HU (leave _Simple_ app on HS foreground)
14. Allow HS to sit idle for 2 minutes
15. Launch _Screens_ app on the HS and then HU

Note the "Press **Back** HK" referred to in the above steps is a HK on the OEM's HU.  Pressing this HK takes the HU screen from the app's screen back to the app launcher screen.
Also note, I don't think the waiting periods are necessary but that is how the tester did the repro.

##### Expected Behavior
App should not be given UnregisterAppInterface (success:false) from an old force-unregister and/or should not disconnect from router if success:false.

##### Observed Behavior
App is disconnected even though it continues to get messages from SDLCore.

##### OS & Version Information
* Android Version: Samsung Galaxy S7 on 6.0.1
* SDL Android Version: 4.4.0
* Testing Against: Custom HMI; SDLCore internal build based on 4.1.2 tag plus a few hotfixes

##### Test Case, Sample Code, and / or Example App
I tried to add the APKs for the above apps but apparently github doesn't like big files.  Please contact me if you want the full logcat log or the apps that were used in testing.

**Comment by joeygrover** [comment]
Fixed with #682

**Comment by E-SAITO-TMC** [comment]
@joeygrover -san,
It is not fix yet.
We reproduce this issue.
Core：6.1.0
Proxy：4.11.0(Android)
device：Pixel（Android8.0）

Could you confirm again?
Thank you!
