### ISSUE TITLE
cycleProxy should not be run after Proxy Disposed

### ISSUE THREAD

**Issue by BrandonHe** [smartdevicelink/sdl_android#661]
### Bug Report
There has memory leak in current proxy after proxy is disposed.

While proxy send UnRegisterApp to core and then handle UnRegisterApp message from SDL_Core, in UnRegisterApp handler, proxy should be disposed, the variable `_proxyDisposed ` has set to `true`,  at this time, the proxy LifecycleManagement should not be run, but there has a problem:
proxy still can cycle according to the SdlProxyBase._advancedLifecycleManagementEnabled in SdlProxyALM.

So, currently proxy has memory leak issue.

Before dispose, the reference tree see below:
![34137040-ad1e1f4e-e4a3-11e7-9415-36df6688070a](https://user-images.githubusercontent.com/13449160/34190102-de9fc636-e579-11e7-9b13-1204419ce804.png)

After disposed, the proxy still can run `cycleProxy`, see blow:
![34137072-dfad188e-e4a3-11e7-9956-21ecb400cbc7](https://user-images.githubusercontent.com/13449160/34190105-e3451e48-e579-11e7-8ba5-7cc84f65af9c.png)

**Comment by brettywhite** [comment]
Hey @BrandonHe Thanks for the issue and PR.

I've been trying to replicate how you did this and had a question. I've tried using both legacy bluetooth and multiplexing bluetooth. After calling `proxy.dispose()` I cannot get the proxy to cycle. (without calling dispose, it cycles properly). Do you mind sharing your setup in which you were able to trigger a cycle after dispose was called?

Thanks!

**Comment by brettywhite** [comment]
Hi @BrandonHe,

Please let me know. I will give this another day and then mark as closed. 

Thanks
