### ISSUE TITLE
Too many SDL Router services running

### ISSUE THREAD

**Issue by jeffmalick** [smartdevicelink/sdl_android#668]
### Bug Report
We have seen a few occurrences of multiple SDL Router services running simultaneously.  Our OEM requires a special case which means that, when HS connected to HU, there should be two Router services, one with open-source BT UUID and one with custom BT UUID.  But we have seen cases where there were three routers, one was ours while connected to HU and two others.

##### Expected Behavior
In our case, at most two SDL Router services, in normal case only one service.

##### Observed Behavior
Three SDL Router services were observed running:

```
root@imx6qsabreauto:~# sdptool browse 8c:3a:e3:ff:7c:ca
Browsing 8C:3A:E3:FF:7C:CA ...
...
Service Name:  SdlRouterService
Service RecHandle: 0x1000b
Service Class ID List:
  UUID 128: 936da01f-9abd-4d9d-80c7-02af85c822a8
Protocol Descriptor List:
  "L2CAP" (0x0100)
  "RFCOMM" (0x0003)
    Channel: 5
...
Service Name: SdlProxy
Service RecHandle: 0x1000f
Service Class ID List:
  UUID 128: 936da01f-9abd-4d9d-80c7-02af85c822a8
Protocol Descriptor List:
  "L2CAP" (0x0100)
  "RFCOMM" (0x0003)
    Channel: 7
...
Service Name:  SdlRouterService
Service RecHandle: 0x10010
Service Class ID List:
  UUID 128: xxyyzz...
Protocol Descriptor List:
  "L2CAP" (0x0100)
  "RFCOMM" (0x0003)
    Channel: 8
```

##### OS & Version Information
* Android Version: various
* SDL Android Version: 4.4.0 (at least in our apps)
* Testing Against: our internal SDL test apps and our OEM’s companion app and at least two production SDL apps with an SDL library that supports multiplexing (not sure what versions they have)

**Comment by joeygrover** [comment]
In your log there are only two router services and a proxy listening to its own RFCOMM channel. It is likely that proxy service wasn't able to connect to one of the router service for some reason and by design it reverts to having its own RFCOMM channel to listen to. We have seen issues in the past where on Android O the library wasn't able to find other router services due to a new limitation in the OS. We've made changes to the latest version of the library to handle this the best it can, but until all the apps are updated it is likely to see duplicate router services on Android O.

**Comment by Tnnnguyen** [comment]
+1 for Joey's comment.
Also this behavior should only be found on Android O devices. @jeffmalick you are stating that it's found on various Android versions. Could you please confirm?

**Comment by jthrun** [comment]
I can confirm.  The sdptool output from above comes from a Nexus 5 with Android v5.0.1

**Comment by joeygrover** [comment]
Again, the output above only shows two router services, which according to the original post is expected (1 with SDL UUID,and a second with custom UUID). There is an SdlProxy service that has obtain an RFCOMM channel itself as well. Meaning, this is not an actual issue unless I'm missing something.
