### ISSUE TITLE
Android O, Unable To Start Router Service And Unable to Connect

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_android#671]
### Summary
Upon startup, apps on devices running Android O try to query for running services using a different flow. When they find no such service, they will attempt to find an eligible service and start it. The problem is that if there is any issue in starting this eligible service, no service is running and apps cannot connect.

Such problem can occur if the eligible service belongs to an app that defines its SdlReceiver.java and SdlRouterService.java classes in two separate packages. See more [here](https://github.com/smartdevicelink/sdl_android/issues/648).

The end result can be a critical bug where none of the Android Sdl enabled multiplexing apps running on Android O devices can connect as long as the problematic eligible app is still installed (or not updated).

**Flow**:
- Wake up router, get a list of installed Sdl enabled apps [here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L205).
- Sort the list, get the first app in the list and build an intent from it [here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L207-L227). If the problematic app is first on the list, it will always end up at first until being deleted or updated.
- Use the first app and start its router service [here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L238-L239) . If it cannot be started, nothing happens resulting in a dead end for apps trying to connect thereafter.

### Reproduction Steps
**Precondition**: 
- Device has no Sdl enabled multiplexing app.
- All apps being used are Sdl enabled multiplexing apps with 4.4.0 Sdl library

**Steps**:
1. Install App A which has SdlReceiver.java and SdlRouterService.java defined in different packages
2. Install App B
3. Install App C

### Expected Behavior
App A starts its own router service and connects through the service
App B either binds to App A's router service or reverts to legacy Bluetooth
App C either binds to App A's router service or reverts to legacy Bluetooth

### Observed Behavior
App A cannot start its own router service; cannot connect
App B tries to start App A's router service unsuccessfully; cannot connect
App C tries to start App A's router service unsuccessfully; cannot connect

### OS & Version Information
* Android Version: Android Oreo
* SDL Android Version: 4.4.0

### Proposed Solution
We should try our best to find out if the intended and eligible router service can be started. If it cannot be started, we should use the next router service in the sorted list and attempt to start that router service until we exhaust the list.

**Comment by joeygrover** [comment]
No longer an issue with #683 being merged
