### ISSUE TITLE
[SDL 0140] Android Manifest Metadata

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_android#683]
Proposal: [Android Manifest Metadata](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0140-android_metadata.md)

> The current Android library relies on a lot of internal methods and functions that try and prevent developers from making changes to their apps. However, as Android becomes more and more strict on what system level methods are available the SDL library will need to move to more conventional methods to accomplish certain goals. One of the ways to achieve this is requiring developers to add metadata fields to the `SdlBroadcastReceiver`. This will allow the library to query all SDL enabled apps and retrieve attributes about them without having to perform any inter-app communication.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/395

Steering Committee Decision:

> It was noted in the Steering Committee that an app partner would only have to include the first line (`router_service_version`) in their manifest to implement this change at a minimum. The other lines are for corner case integrations.  It was also clarified that the package “com.livio” was used in the proposal as an example declaration and would be specific to each app partner’s integration. Finally, it was confirmed that this information would be included in the Android Guide once implemented.  The Steering Committee then voted to accept this proposal.

**Comment by joeygrover** [comment]
Fixed with #686
