### ISSUE TITLE
Potential crash in SdlRouterService.java

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_android#689]
### Bug Report
In `SdlRouterService.java`, `deployNextRouterService` method, 2 cases where the library could crash with an IndexOutOfBoundException:
1. List size = n, and i = n - 1
2. List size is 1 (special case of 1.)

The problem is with this index access:  [here](https://github.com/smartdevicelink/sdl_android/blob/develop/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L825)
```
SdlAppInfo nextUp = sdlAppInfoList.get(i+1);
```

##### Expected Behavior
Library would not crash.

##### Observed Behavior
Library would crash.

**Comment by joeygrover** [comment]
Not an issue. See the conditional before that statement.

**Comment by joeygrover** [comment]
Fixed with #690
