### ISSUE TITLE
always show the Running SDL service if turn on the bluetooth even no device connected in Android Pixel

### ISSUE THREAD

**Issue by yingchun1** [smartdevicelink/sdl_android#698]
### Bug Report
[It will always show the Running SDL service if turn on the bluetooth even no device connected in Android Pixel, OS 8.1]

##### Reproduction Steps
1. Start the app which support the SDL.
2. Turn on device bluetooth, but not pair to other device.
3. It will show the Running SDL service with "Connected to" indicator.

##### Expected Behavior
[it should only be visible when connect to a TDK device]

##### Observed Behavior
[User will confuse about this service and we have already received some inner tester's complain about this.]

##### OS & Version Information
* Android Version: [Android Pixel with O(8.1) ]
* SDL Android Version: [4.4]
* Testing Against: [In android 7.1, 8.0, no such issue, may introduced by new OS design]

![image](https://user-images.githubusercontent.com/20849782/37135165-f4f30d9a-22d6-11e8-8a25-92fb360abb04.png)

**Comment by yingchun1** [comment]
Sometimes it can not show "Connect to SYNC" even connected to SYNC already.

**Comment by joeygrover** [comment]
Fixed with #699. Note that a foreground notification must be present during initial connection/start up due to Android O limitations. See #699 for more explanation.
