### ISSUE TITLE
Hello ,

### ISSUE THREAD

**Issue by athul7pk** [smartdevicelink/sdl_android#737]
I am working in HU (car side) . I dont know anything about android  is there any prebuilt apk for application available for testing?
I am using Genivi Linux with SDL in intel board.
While connecting phone with HU ,phone is showing No installed app work with this usb.....
It willl be realy helpful if some one can share any test apk or any application that support  sdl in playstore

**Comment by bilal-alsharifi** [comment]
There are some SDL enabled apps on Play Store like iHeartRadio, Pandora, and Ford+Alexa. You can try any of them for testing. There are also some open source app samples on Github:
https://github.com/smartdevicelink/hello_sdl_android
https://github.com/smartdevicelink/sdl_mobileweather_tutorial_android

If you have more questions, please ask the [SDL community on Slack](http://slack.smartdevicelink.com). GitHub is more like for bugs reporting.
