### ISSUE TITLE
Insufficient Entropy CWE ID 331 in RTPH264Packetizer.java 

### ISSUE THREAD

**Issue by appledragon** [smartdevicelink/sdl_android#747]
### Bug Report
Standard random number generators do not provide a sufficient amount of entropy when used for security purposes. Attackers can brute force the output of pseudorandom number generators such as rand()，Random()

Recommendations
If this random number is used where security is a concern, such as generating a session identifier or cryptographic key, use a trusted cryptographic random number generator instead.

note: this is reported by veracode

**Comment by brettywhite** [comment]
This is a non-issue for this class, as it is not meant to be security related. The primary purpose of using RTP is to carry timestamp information along with the data, and that is facilitated in `RTPH264Packetizer.java`. It is not used for encryption or the generation of cryptographic items such as session keys or tokens. Additionally, many OEMS do have specific security managers that they use to encrypt the stream, but these are supplied by the OEM, and not included in this repository. 

If you'd like to discuss any concerns, the best place is in our slack channel: http://slack.smartdevicelink.com/
