### ISSUE TITLE
Setting Destination 

### ISSUE THREAD

**Issue by heenak** [smartdevicelink/sdl_android#752]
I am trying to set destination over HMI device using HMI emulator but unable to code the softbutton available on the screen neither I am able to see where the destination location is set.

Kindly help me in using the SendLocation API

**Comment by brettywhite** [comment]
Hi @heenak 

Please take a look at the documentation at https://smartdevicelink.com/ 

If you have questions, the community on slack is the best place to ask: http://slack.smartdevicelink.com/

Thank you
