### ISSUE TITLE
[SDL 0166] Use Android Annotations Library

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_android#755]
Proposal: [Use Android Annotations Library](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0166-use-android-annotations-library.md)

> This proposal is to include the annotations dependency and start using it in the SDL Android library. Java annotations allow developers to provide hints to the compiler and code inspection tools. This ensures that code issues do not propagate which enhances the overall quality of the code.

Review: smartdevicelink/sdl_evolution#484

**Comment by joeygrover** [comment]
Annotations library is now included in develop. Including the new annotations will be a passive effort from here on out on old code.
