### ISSUE TITLE
Match iOS APIs

### ISSUE THREAD

**Issue by BrettyWhite** [smartdevicelink/sdl_android#759]
## Match iOS APIs

SDL Android currently is missing many nice manager APIs that are present in its iOS counterpart. This issue will be attached with a branch to go along with an evolution proposal. Please ignore for now.

**Comment by brettywhite** [comment]
base branch: https://github.com/smartdevicelink/sdl_android/tree/feature/sdlmanager

**Comment by BrettyWhite** [comment]
Closing as initial Evo pro was finished. More specific issues for choice set and menu managers can be added later
