### ISSUE TITLE
Lockscreen status reports wrong when app launches in Background

### ISSUE THREAD

**Issue by mschwerzler** [smartdevicelink/sdl_android#773]
### Bug Report
The lockscreen status does not report back correctly when the app is launched in background.

##### Reproduction Steps
1. Build an app that is able to be launched in background and an Android activity that responds to lockscreen events.
2. Connect to a TDK or core instance.
3. Simulate the driver distraction.

##### Expected Behavior
The lockscreen appears on the Android device.

##### Observed Behavior
The lockscreen does not appear on the Android device

##### OS & Version Information
* Android Version: Android P
* SDL Android Version: 4.5.0
* Testing Against: Pixel

**Comment by askirk** [comment]
@mschwerzler Could you clarify whether the app was running in background on the phone or that the app's HMI Level on the TDK was `Background`?

**Comment by mschwerzler** [comment]
@askirk It was running in background on the TDK.

**Comment by askirk** [comment]
https://github.com/smartdevicelink/sdl_android/pull/813 will clear up existing issues with lockscreen
