### ISSUE TITLE
Question about the security connection between vehicle head units and phone app

### ISSUE THREAD

**Issue by yingchun1** [smartdevicelink/sdl_android#774]
Question: Security connection?

Are there some verification process that to ensure the end user are connected to the real vehicle head units otherwise a fake one which simulate service like the real one and the hacker then can stolen some informations from the communicate between the App and the "fake vehicle head units"?

**Comment by bilal-alsharifi** [comment]
If you have any questions, please ask the [SDL community on Slack](http://slack.smartdevicelink.com). GitHub is more like for bugs reporting.
