### ISSUE TITLE
[SDL 0174] Deprecate RPCRequestFactory

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_android#792]
Proposal: [Deprecate RPCRequestFactory](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0174-deprecate-rpc-request-factory.md)

> This proposal is to deprecate the `RPCRequestFactory` class and start using RPC constructors directly to create new RPC instances.

Review: smartdevicelink/sdl_evolution#509

Steering Committee Decision:
> The Steering Committee voted to accept this proposal with revisions. The revisions will be clarifying that the proposal itself is not a major change, but instead, at the time of the next major change, the deprecated class will be removed.

> The proposal .md was updated on June 13, 2018 to include the agreed upon revisions.

**Comment by brettywhite** [comment]
Completed with #791
