### ISSUE TITLE
NullPointerException in PerformAudioPassThru get method

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_android#80]
For the [PerformAudioPassThru](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/PerformAudioPassThru.java#L221-223) class, if a new PerformAudioPassThru object is made and calls getMaxDuration a NullPointerException occurs trying to return an int.

**Comment by mrapitis** [comment]
Very true, we should be returning an Integer type here (which allows nulls).
