### ISSUE TITLE
Android 8.1 crashes with "invalid channel for service notification"

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/sdl_android#843]
### Bug Report
App partner is reporting ~4000 crashes a day with the following message:

> android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=sdl_notification_channel pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE) 
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1867) 
> at android.os.Handler.dispatchMessage(Handler.java:106) 
> at android.os.Looper.loop(Looper.java:164) 
> at android.app.ActivityThread.main(ActivityThread.java:6753) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)   

One possible root cause is [SdlRouterSErvice.java#L1073](https://github.com/smartdevicelink/sdl_android/blob/164e1a228b3a047df23c0b4fe7bece2cd301f289/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L1073) as it's using a deprecated method to build the notification. Also reported in this [startForeground fail after upgrade to Android 8.1](https://stackoverflow.com/questions/47531742/startforeground-fail-after-upgrade-to-android-8-1) at StackOveflow. The partner is targeting API 27 in their app (min sdk is not known yet).

##### OS & Version Information
* Android Version: As reported it's always Oreo 8.1
* SDL Android Version: 4.6.2
* App target version: API 27 (8.1)
* Testing Against: Radioplayer UK

**Comment by kshala-ford** [comment]
More infos on that from Android documentation (see [here](https://developer.android.com/reference/android/app/Notification.Builder#Notification.Builder(android.content.Context)))

> public Notification.Builder (Context context)
> This constructor was deprecated in API level 26.
use Notification.Builder(Context, String) instead. All posted Notifications must specify a NotificationChannel Id.

**Comment by theRealBrett** [comment]
Because they are targeting Oreo are they creating their own notification channel (as you found in the SO article)? It's in the [docs](https://smartdevicelink.com/en/guides/android/getting-started/integration-basics/)  under the section: Entering the Foreground

**Comment by bilal-alsharifi** [comment]
That is strange. I have just tried the exact same code that you posted and it worked for me without any issues on Pixel 2 with Android 8.1 and targetting Android 27. I don't think the deprecated method will cause an issue neither.

**Comment by SilvioDC-Ford** [comment]
Since the use a different channel id, the crashlog is pointing to the SDLRouterService:
> channel=sdl_notification_channel

**Comment by joeygrover** [comment]
Can you provide which phones are throwing this error? The error itself should theoretically propagate every time the library is used if there was an issue with the notification creation. We can  attempt to put in some band aid fixes to stop the ANR, but it's tough to pinpoint why this is happening just based on the code logic itself.

**Comment by SilvioDC-Ford** [comment]
The reporting phones are in descending crash order:

>P20Pro, OnePlus5, OnePlus6, P20, Pixel 2, Nexus 5x, Nokia 8, OnePlus5T, Swift 2, Nokia 6, Pixel XL, Honor 10, Nokia 5, Nokia 7 plus, Nexus 6P, OnePlus3T, Pixel 2 XL, Pixel, Nokia 6.1, Mi A1

**Comment by SilvioDC-Ford** [comment]
They are using the one from helloSDL:
private static final int FOREGROUND_SERVICE_ID = 111;

**Comment by SilvioDC-Ford** [comment]
The developer thinks that it could have something to do with the removal of the channel in the SDLRouterService after the timeout.
It could be, that the crashes occured when the phone connected to other BT devices than Sync headunits.

**Comment by joeygrover** [comment]
I've attempted to put some safeguards in place (See #847 ) to help with the issue, but trying to find repro steps for the problem is proving to be extremely difficult.

**Comment by joeygrover** [comment]
After a lot of investigation here is what we believe to be happening. There is a race condition between the completed of the `enterForeground` and if the timeout handler is called. If the timeout handler is called after line [1121](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L1121) but before line [1133](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L1133), the channel will get deleted and therefore become invalid. So I do believe synchronizing the methods to enter and exit foreground will actually solve the issue (See #847)

**Comment by SilvioDC-Ford** [comment]
Great that you could find the issue and create a fix that quickly.
Thanks a lot!

**Comment by joeygrover** [comment]
No problem. After some internal discussion we decided this should qualify for a hotfix release. PR submitted (#849) and will have the team review/test and hopefully release today or tomorrow.
