### ISSUE TITLE
SystemCapabilityManager false positive

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_android#844]
### Bug Report
The `SystemCapabilityManager` is returning false positive result if the module does not include a value for the capability. 

See [here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/proxy/SystemCapabilityManager.java#L60)

##### Reproduction Steps

Check a capability that was not included in the RAI response.
The SCM will store a value of null in the map and returned true that the entry exists.

##### Expected Behavior

Returns false if the value is null

**Comment by BrettyWhite** [comment]
Closed with #845
