### ISSUE TITLE
[SDL 0118] Video Streaming Backgrounded String

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_android#846]
Proposal: [Video Streaming Backgrounded String](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0118-video-background-string.md)

> Display a string of text on the head unit screen when the app leaves the foreground.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/356

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with revisions. The revisions will include updating the text to reflect Ford legal's preference, as described in this comment from Ford.  There was also discussion on the call regarding translations of this text. It was determined these could be discussed at a later date upon implementation, but would likely not require a separate Evolution Proposal for review.
> The proposal .md file was updated to reflect these revisions on 8/27/18.

**Comment by joeygrover** [comment]
I don't believe this actually affects the Android platform. Apps can stream in the background and therefore don't need to display a string on the head unit. I am closing for now, but if found to be necessary at a later time we can reopen.
