### ISSUE TITLE
DeviceUtil.isEmulator() returns false on Android Emulator 

### ISSUE THREAD

**Issue by bilal-alsharifi** [smartdevicelink/sdl_android#854]
### Bug Report
Some unit tests fail when they are run locally on newer Android Emulators. The issue is happening because `com.smartdevicelink.test.util.DeviceUtil.isEmulator()` is returning `false` when it is supposed to return `true` on the emulator.

##### Reproduction Steps
1. Create a new Android Emulator
2. Run `com.smartdevicelink.SdlConnection.SdlConnectionTest` 

##### Expected Behavior
Tests should pass

##### Observed Behavior
Tests fail

**Comment by BrettyWhite** [comment]
Closed w/ #855
