### ISSUE TITLE
OnSystemRequest has a lot of bugs

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#86]
[OnSystemRequest](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnSystemRequest.java) doesn't really follow the guidelines and practices of the rest of the project.  It seems like it was hurriedly thrown together and therefore, it has a lot of bugs.

I can see [here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnSystemRequest.java#L44-57) that the class is attempting to create a JSON object from the binary bulk data.  If the BulkData is valid, it will save 2 global variables, `httpreqparams` and `myJSONObj`.  If the bulk data is not valid, both of these variables will be null.

In the [setHeaders method](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnSystemRequest.java#L125-131), if the `httpreqparams` is null, it will cause a NullPointerException crash.

The body of the request is even more confusing.  In the [getBody method](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnSystemRequest.java#L86-114), it is trying to read from `httpreqparams` if that's not null.  Even though `httpreqparams` is already the object returned from the `"HTTPRequest"` key, the code is reading the exact same value from the original bulk data and then reading the `"body"` key from that.  If the `httpreqparams` is null, the code just returns the original bulk data as a string, which I don't really understand.  Why are we just blindly assuming that whatever is in the bulk data is the body of an HTTP request in this one case?  In addition, in the [setBody method](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/OnSystemRequest.java#L116-122), the body information is stored in the parameters hashtable, which isn't even where it came from and obviously doesn't belong here.

I think this whole class should be re-written, to be honest.

**Comment by mrapitis** [comment]
Now that some of the dust has settled and the JSON within OnSystemRequests binary data has become better defined we can perform some cleanup on the class.  Yes initially, the class was written quickly as we were concerned with getting policy table updates working asap. Re-writing the entire class is overkill.  

I would suggest we include this as an agenda item on our next SmartDeviceLink open source review meeting.

**Comment by mikeburke106** [comment]
Ok, scheduled for review.  Re-writing a class isn't the end of the world - obviously most of the setters and getters would remain the same, so it won't change entirely.  I'm basically just trying to say this won't be a trivial fix and will require a good amount of change and will need to be reviewed thoroughly.

This class will only work correctly if the hashtable constructor is used.  There's no way to set the headers and body data other than through the hashtable constructor, which makes unit testing this class very difficult if not impossible.  If we attempt to create a class like we do all the other RPCs, it will look something like this:

```java
// BIN_DATA, HEADERS and BODY defined as constants

OnSystemRequest onSystemRequest = new OnSystemRequest();

// does practically nothing because bulk data is only used in hashtable constructor
onSystemRequest.setBinData(BIN_DATA); 

// CRASH - NullPointerException due to `httpreqparams` not being initialized
onSystemRequest.setHeaders(HEADERS);

onSystemRequest.setBody(BODY);

// always returns null since `httpreqparams` and `myJSONObj` are both null
String body = onSystemRequest.getBody();

// always returns null since `httpreqparams` is null
Headers headers = onSystemRequest.getHeader();
```

This needs to change soon because Livio's co-ops are working on writing unit tests for the mobile libraries and we need to be able to test all the RPC objects against the spec.
