### ISSUE TITLE
SDL is causing "app is using battery" notification in Oreo

### ISSUE THREAD

**Issue by StevenDai-IBM** [smartdevicelink/sdl_android#894]
[Delete any non-applicable sections, but we may ask for more information.]

### Bug Report
On Oreo, I'm getting "app is using battery" when I put app in background. The same result I get with Hello SDL.

##### Reproduction Steps
1. turn on bluetooth
2. restart the phone
3. open the app then put in background

##### Expected Behavior
No notification

##### Observed Behavior
seeing "App is using battery" notification on Oreo

##### OS & Version Information
* Android Version: Oreo (8/8.1)
* SDL Android Version: 4.6.2
* Testing Against: Samsung S7, S8, S9, etc

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by joeygrover** [comment]
Not an issue. 

This is as designed. The `SdlService` is running in the background and therefore the OS is informing the user.
