### ISSUE TITLE
Hello Sdl app does not come to the foreground on click, only hightlighted (4.7.0-rc1).

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_android#897]
### Bug Report
Hello Sdl app does not come to the foreground

##### Reproduction Steps
1. Install Hello Sdl app using 4.7.0-rc
2. Turn BT off on device
3. Turn on head unit, connect USB cable
4. Tap "Apps", Hello Sdl app detected on head unit
5. Tap on Hello Sdl icon, icon is highlighted but app does not come to the foreground on head unit

##### Expected Behavior
App comes to the foreground on head unit (HMI_FULL) 

##### Observed Behavior
App does not come to the foreground on head unit. App icon is highlighted for about 10 seconds then comes back to normal color.

##### OS & Version Information
* Android Version: 8.1.0, Pixel XL
* SDL Android Version: 4.7.0-rc1, using multi_high_bandwidthDebug build

**Comment by BrettyWhite** [comment]
As i said in the other PR, please test against hardware that is not SG3 and rule that out. Thanks
