### ISSUE TITLE
Hello Sdl app automatically backs out of FULL_HMI screen

### ISSUE THREAD

**Issue by Tnnnguyen** [smartdevicelink/sdl_android#898]
### Bug Report
When Hello Sdl app is in the foreground, it automatically backs out of it

##### Reproduction Steps
1. Install Hello Sdl app using 4.7.0-rc
2. Turn BT off on device
3. Turn on head unit, connect USB cable
4. Tap "Apps", Hello Sdl app detected on head unit
5. Tap on Hello Sdl icon, icon is highlighted but app does not come to the foreground on head unit
6. Tap on Hello Sdl icon again while it's still highlighted, observe app comes to the foreground
7. Wait for a few seconds

##### Expected Behavior
App stays on the foreground (HMI FULL)

##### Observed Behavior
App automatically backs out, radio screen takes over

##### OS & Version Information
* Android Version: 8.1.0, Pixel XL
* SDL Android Version: 4.7.0-rc1, multi_high_bandwidthDebug build

**Comment by BrettyWhite** [comment]
@Tnnnguyen are you using the repo that we are going to remove or the hello sdl that is now packaged in that branch?

**Comment by Tnnnguyen** [comment]
@BrettyWhite it's the hello sdl version that is packaged in the branch.

**Comment by BrettyWhite** [comment]
This has been observed behavior of the Sync Gen 3 head units for apps that are not navigation and connect through the AOA transport. It is most likely a gen 3 issue. It does not do this on other SDL devices or vm's we've tested. If the app is a navigation app this will not happen as the video will start streaming. 

You did not define which head unit you tested with in your initial report. Please check against what I just described and either close or update the issue. 

Thanks
