### ISSUE TITLE
Wi-Fi secondary transport cannot be established when HU does not offer Internet connectivity and the phone has mobile network

### ISSUE THREAD

**Issue by shoamano83** [smartdevicelink/sdl_android#899]
(These information are provided by Ford team - thanks!)

### Bug Report
 
As detailed in the Android Developer Blog linked below, when connecting to a Wi-Fi device that has no internet connectivity, the Android application (mobile library in our case) must select the correct network (e.g. wi-fi or cellular network) to route traffic to. In our case, we are utilizing a secondary transport with a wi-fi network device, the `MultiplexTcpTransport` class in the Android mobile library needs to be updated to reflect this logic.
https://android-developers.googleblog.com/2016/07/connecting-your-app-to-wi-fi-device.html?m=1

##### Reproduction Steps

1. Build the SDL library with an application that downloads video from the internet (for testing purposes we updated the video streaming sample app to download a video as opposed to using a locally residing file).
2. Register the application with SDL core and activate the app on the HMI (put the app into full).
3. Take note that many mobile devices (including the Google Pixel) will not be able to create a TCP connection to SDL Core for secondary transport.

##### Expected Behavior
The video app can download a video file from internet through mobile network while streaming video to the head unit over Wi-Fi connection.

##### Observed Behavior
The app cannot create a TCP connection to SDL Core over Wi-Fi network.

Note: the issue does NOT occur if the phone has disabled mobile data.

##### OS & Version Information
* Android Version: Google Pixel with Android 8
* SDL Android Version: https://github.com/mrapitis/sdl_android/commit/15bf534805eb7b0a53f5dbadf65af68e670b8cb4
* Testing Against: Ford's next-gen HU. The HU has Wi-Fi network and does not offer internet connection over it.

##### Test Case, Sample Code, and / or Example App
N/A

**Comment by shoamano83** [comment]
Hi, I'm working with Ford team and I think I could reproduce the issue. Here's my set up, if anyone is interested.

- A Linux PC (Ubuntu 16.04 LTS) with Bluetooth dongle and ethernet port
  * SDL Core: latest `develop` (https://github.com/smartdevicelink/sdl_core/commit/28235f88a6733106a7e8a0d490dfb16a5f374a33)
  * HMI: sdl_hmi with a little update for video streaming, please refer to 

- A Wi-Fi access point with DHCP server enabled and has no Internet connection. The PC and the access point is connected through ethernet.

- Android Phone: Xperia Z3+ (Android 6.0)
  * SDL app: sample app from https://github.com/shoamano83/sdl_video_streaming_android_sample/commit/843b3ca5d1cc2b59e31a7e6c16ee6cd63a2ae98a
  * SDL Library: commit f099f7c6431dd661bd314396722154c57d1499c0 from `release/4.7.0-rc1` branch

Steps are to launch the SDL app, enable Bluetooth on the phone and establish Bluetooth connection with Core, then after registration make the app into FULL level.
The router service tries to establish a TCP connection to Core and fails, since Android system will by default route the connection to mobile network when the Wi-Fi network has no Internet connectivity. 

Logs:
[20181010_sony_xperia_sdlstreaming.log](https://github.com/smartdevicelink/sdl_android/files/2463256/20181010_sony_xperia_sdlstreaming.log)
[20181010_sony_xperia_router.log](https://github.com/smartdevicelink/sdl_android/files/2463257/20181010_sony_xperia_router.log)

**Comment by theresalech** [comment]
Closed via #900
