### ISSUE TITLE
Need all backwards compatibility issues documented

### ISSUE THREAD

**Issue by joeygrover** [smartdevicelink/sdl_android#90]
As we get further into refactoring and optimizing classes it seems we keep running across little "hacks" that are put in place to support older SDL versions and hardware. We need a comprehensive list that details all known issues in this regard. Does anyone know if this information is documented anywhere? I'm going to assign @Heath-FoMoCo and, if possible, he can assign someone from his team to work on this as they probably are the most knowledgable. This is incredibly important moving forward.  

These types of issues can be added to unit tests so we can make sure we aren't breaking anything.

**Comment by mikeburke106** [comment]
Here are 2 issues I've discovered so far:

  * Legacy versions of SDL core don't ensure double values have a decimal point.  A double without a decimal point is read in as an integer value, which can cause casting issues.
  * #89 - VrCapabilities value can be either "Text" or "TEXT", so case is ignored in enum lookup

**Comment by idamaster** [comment]
I will attempt to write down what I tend to know. a couple of others that might be valuable to know. 
* PerformInteraction in older implementations always need an non-null, non-blank initialPrompt parameter even if the interactionType is "MENU" so some apps send a prompt of TTSChunk SILENCE of 1 ms. 
* Old vehicles reject RPC RegisterAppInterface with a major version > 1
* Old vehicles reject protocol StartSession/Service request with protocol version > 1

**Comment by mikeburke106** [comment]
@smartdevicelink/android - BUMP.

Thanks @idamaster.

Livio is working to thoroughly understand the protocol layer of the spec, so it would be really helpful if we could get some more responses on this issue.

Here are some other issues the Livio team has noticed:
  * Spec says correlation ID is 4 bytes, but legacy implementation of core rejects IDs larger than 2 bytes.  When this happens, correlation ID of the response will be null, potentially causing runtime exception crash.

```java
int corrId = response.getCorrelationID(); // CRASH
```

  * Code has "reserved" correlation IDs for RegisterAppInterface, UnregisterAppInterface, Heartbeat and Policies, but these reserved IDs are not documented in the spec.  These reserved IDs are highest 2-byte values even though correlation ID should be able to go up to 4 bytes.  There is no documentation for developers to know that these reserved values cannot be used for normal RPC requests

```java
private static final int    REGISTER_APP_INTERFACE_CORRELATION_ID = 65529,
                            UNREGISTER_APP_INTERFACE_CORRELATION_ID = 65530,
                            HEARTBEAT_CORRELATION_ID = 65531,
                            POLICIES_CORRELATION_ID = 65535;
```

  * Some RPCs require bulk data (PutFile), but these specific RPCs are not documented.  XML spec doesn't contain any info about RPCs requiring bulk data.

**Comment by mikeburke106** [comment]
Marking for discussion on the next call since nobody is responding on this thread.  This is a really important area for maintainers to understand if we want to maintain backwards compatibility with old head-units.  If we can't get a comprehensive list, it will be impossible for us to maintain backwards compatibility moving forward.

Please do your best to have a list of issues for us by the next call.

**Comment by mikeburke106** [comment]
Gen 1.1 hardware always sends a list of SoftButtonCapabilities objects, but Gen 3 will only send a single SoftButtonCapabilities object.  See #148.

**Comment by justinjdickow** [comment]
Justin to move these known legacy considerations over to a wiki in an appropriate repo and close this issue.

**Comment by joeygrover** [comment]
@justinjdickow How's this coming?
