### ISSUE TITLE
No way to access VehicleType using SDLManager in SDL release 4.7.2

### ISSUE THREAD

**Issue by ashwink11** [smartdevicelink/sdl_android#928]
### Bug Report
[No Way to access Vehicletype Information using SDLManager]

##### Reproduction Steps
API not provided to access VehicleType Information

##### Expected Behavior
VehicleType information should be available to Apps.

##### Observed Behavior
NA

##### OS & Version Information
* Android Version: Android OS 9
* SDL Android Version: 4.7.2
* Testing Against: Ford SYNC

##### Test Case, Sample Code, and / or Example App
NA

**Comment by joeygrover** [comment]
Fixed with #936 and will be contained in next minor release 4.8.0 ASAP.
