### ISSUE TITLE
getRunningServices in SdlBroadcastReceiver is only return caller service in Android O

### ISSUE THREAD

**Issue by yingchun1** [smartdevicelink/sdl_android#940]
### Bug Report
getRunningServices in SdlBroadcastReceiver was deprecated in API level 26. 
As of Build.VERSION_CODES.O, this method is no longer available to third party applications. For backwards compatibility, it will still return the caller's own services.

##### Reproduction Steps
Issue by code scan tool.
As of 2014, Google began classifying Apps that collect the list of Apps on the device as Spyware, as described on page 29 of the Android Security Report:

"Throughout 2014, we have regularly tightened the definition of Spyware, for example in 2014 we began to classify applications that send the list of other applications on the device as Spyware."

##### Expected Behavior
Can still work without using this method.

##### OS & Version Information
* Android Version: Android O
* SDL Android Version: 4.7.1
* Testing Against: Code scan

**Comment by bilal-alsharifi** [comment]
You are right. Though we are using this `getRunningServices` only when Android version is less than O as shown in this line:
https://github.com/smartdevicelink/sdl_android/blob/490be41b20ec4bb4a81837e73eb6ea9bfcea7a8a/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L357

When Android version is O and newer, we use a different method to get the running services.
