### ISSUE TITLE
The screen manager does not clear any graphic set to `null`

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_android#942]
### Bug Report
If the user tries to clear an image from the screen by setting an image field to `null` using the screen manager, the image is never cleared. This is due to the blank artwork always being null. 

In the `TextAndGraphicManager` class: 
```
SdlArtwork getBlankArtwork() {
    if (blankArtwork != null){
        ...
    }
    return blankArtwork;
}
``` 

should be:
```
SdlArtwork getBlankArtwork() {
    if (blankArtwork == null){ /* <- The blank artwork object should be created if not already */
        ...
    }
    return blankArtwork;
}
```

##### Reproduction Steps
1. Create an app using the screen manager. Set the primary graphic field to an image. 
1. Connect the app to a head unit. The image from step 1 should show up in the primary graphic field
1. Set the primary graphic field to `null` using the screen manager.

##### Expected Behavior
The primary graphic image field should be cleared.

##### Observed Behavior
The image from step 1 stays visible.

##### OS & Version Information
* Android Version: 9, API 28
* SDL Android Version: 4.7
* Testing Against: SDL_Core 5.0 and generic_hmi

**Comment by BrettyWhite** [comment]
Closed with #954
