### ISSUE TITLE
[SDL-0214] - Secondary Transport Optimization

### ISSUE THREAD

**Issue by jordynmackool** [smartdevicelink/sdl_android#967]
Proposal: [Secondary Transport Optimization](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0214-secondary-transport-optimization.md)

> This proposal aims to optimize how secondary transports are connected and registered. The original proposal [SDL-0141](0141-multiple-transports.md) stated secondary transports should be connected to and registered on immediately when they are available. This proposal is to change that to connect and register only when necessary by the application.

https://github.com/smartdevicelink/sdl_evolution/issues/652

Steering Committee Decision:

> The Steering Committee voted to fully accept this proposal on 2019-01-15.

**Comment by joeygrover** [comment]
This is already completed for the Android library. Per the 4.7.0 release.

**Comment by joeljfischer** [comment]
@joeygrover Do you have any direction to the PR that this was implemented in? I'm having trouble finding it.
