### ISSUE TITLE
Project should follow Java naming conventions

### ISSUE THREAD

**Issue by mikeburke106** [smartdevicelink/sdl_android#98]
Prior to the next major release of SDL (4.0.0), the project should be refactored to follow recognized Java naming conventions.  Livio is working on a contributor style guide, which will need to be followed for all PRs after we make this change, but it will follow the following guides very closely:

  * [AOSP Java Style Guide](https://source.android.com/source/code-style.html)
  * [Google Java Style Guide](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html)
  * [Oracle Java Style Guide](http://www.oracle.com/technetwork/java/codeconvtoc-136057.html)

Some examples of classes that will need to be fixed are:

  * `HMILevel` -> `HmiLevel`
  * `RPCMessage` -> `RpcMessage`
  * `TTSChunks` -> `TtsChunks`
  * `TCPTransport` -> `TcpTransport`
  * `OpenRPCMessage` -> `OpenRpcMessage`

Similarly, some packages will need to be changed:

  * `com.smartdevicelink.Dispatcher` -> `com.smartdevicelink.dispatcher`
  * `com.smartdevicelink.SdlConnection` -> `com.smartdevicelink.sdlconnection`

These will all, obviously, be backwards-incompatible changes, which is why we will wait until the next major version release to incorporate these changes.

**Comment by mikeburke106** [comment]
The following enums do not follow naming conventions:

  * ImageFieldName (all fields are camel case instead of all caps)
  * TextFieldName (all fields are camel case instead of all caps)
  * MessageType (all fields are camel case instead of all caps)
  * VrCapabilities (all fields are upper camel case instead of all caps)
  * Dimension (leading underscore in front of enum values)
  * BitsPerSample (leading underscore in front of enum values)
  * SamplingRate (leading underscore in front of enum values)
  * ButtonEventMode (no underscores between words)
  * ButtonName (no underscores between words)
  * CharacterSet (no underscores between words)
  * GlobalProperty (no underscores between words)
  * MediaClockFormat (no underscores between words)
  * DriverDistractionState (has redundant prefix)
  * ECallConfirmationStatus (has redundant prefix)
  * HMILevel (has redundant prefix)
  * PowerModeQualificationStatus (has redundant prefix, has duplicate "undefined" values)
  * SdlConnectionState (has redundant prefix)
  * SdlInterfaceAvailablility (has redundant prefix)
  * SoftButtonType (has redundant prefix)
  * SystemContext (has redundant prefix)
  * TriggerSource (has redundant prefix)
  * VehicleDataType (has redundant prefix)

**Comment by MikaylaRay44** [comment]
The variable names in the Names class do not follow convention for final variables either.

**Comment by joeygrover** [comment]
The best practice for this will be do move forward using the correct naming conventions, however, going back to fix old issues that are developer facing brings up more issues than simply accepting the conventions as wrong. Closing this issue with the knowledge that future updates will follow proper conventions.
